### ISSUE TITLE
Iterator<Object[]> DataProvider: indices not working

### ISSUE THREAD

**Issue by mfulton26** [cbeust/testng#1009]
In the below code I expect only 2 tests to run (and pass):

```java
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.util.Iterator;
import java.util.stream.IntStream;
import java.util.stream.Stream;

public class IndicesTest {
    @DataProvider(indices = {7})
    public static Object[][] dataArray() {
        return dataStream().toArray(Object[][]::new);
    }

    @DataProvider(indices = {6})
    public static Iterator<Object[]> dataIterator() {
        return dataStream().iterator();
    }

    private static Stream<Object[]> dataStream() {
        return IntStream.range(0, 8).mapToObj(value -> new Object[]{value});
    }

    @Test(dataProvider = "dataArray")
    public void dataArrayIndices(int index) {
        assert index == 7;
    }

    @Test(dataProvider = "dataIterator")
    public void dataIteratorIndices(int index) {
        assert index == 6;
    }
}
```

However, `dataIteratorIndices` runs 8 times instead of 1 time (and 7 of the 8 fail).

**Comment by krmahadevan** [comment]
@mfulton26 
I doubt if the indices attribute was aimed at working with a Lazy loading Data provider (Iterator powered one is supposed to be a lazy data provider ). I think its supposed to work with the greedy variant (the one that returns a 2D Object array ).

**Comment by mfulton26** [comment]
Why do you say that? Is there some documentation that leads you to believe such?

**Comment by juherr** [comment]
I didn't find any documentation about `@DataProvider(indices = {... })`,  do you ? 

It may be an unsupported beta feature. 

Ping @cbeust

**Comment by cbeust** [comment]
It's supported, just undocumented ;-)

-- 
Cédric

**Comment by mfulton26** [comment]
Well, it is documented in the Javadocs: "Which indices to run from this data provider, default: all" ([DataProvider](http://testng.org/javadocs/org/testng/annotations/DataProvider.html)).

**Comment by mfulton26** [comment]
It would be nice, I think, for this to work with not only `Object[][]` but also `Iterator<Object[]>`. Thanks.

**Comment by krmahadevan** [comment]
@mfulton26 
No I am not saying that support for indices attribute exists only for the greedy data provider flavor, based on any documentation. I am saying that, because I feel logically it makes sense. The greedy data provider variant would already know how many total iterations are present and as such, if you pick one or more indices via the indices attribute, it would get filtered. But the lazy variant of data provider using the Iterator, basically gets to know only one record at a time. So TestNG would keep coming back to the data provider for every iteration. So how would it be able to handle the index values, in this scenario. This was what made me believe that indices was perhaps never meant to be used with the lazy data provider variant. 

I then went back to look at the code. [This](https://github.com/cbeust/testng/issues/1009#issuecomment-201383713) section basically deals with indices only if they are of the greedy variant and as you can see in [this](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/MethodInvocationHelper.java#L153-L155) section, if its a lazy data provider powered by an iterator, the "indices" attribute is NOT considered.

**Comment by krmahadevan** [comment]
@mfulton26 
So in the case of `Iterator<Object[]>` I think your data provider implementation should basically deal with the logic of filtering out things via some other mechanism.

**Comment by mfulton26** [comment]
I see. Well I can certainly drop/skip elements on my own but it looked like TestNG was already supposed to do such for me. If it isn't meant to be supported then perhaps the documentation can be updated to reflect such. However, keeping track of the current index while iterating through a collection is simple enough so adding/fixing support for indices seems straight forward enough.

**Comment by mfulton26** [comment]
FYI: I just realized that this also means that running attempting to run only failed tests from a previous run doesn't work because the `invocation-numbers`/`indices` is not honored. Maybe I just need to change to using `Object[][]` and increase my memory usage (if I can).

**Comment by mfulton26** [comment]
FYI: testng.xml `/suite/test/classes/class/methods/include/@invocation-numbers` does work with `Iterator<Object[]>`.

**Comment by krmahadevan** [comment]
@mfulton26  I didn't get that last comment. What did you mean ? It would be good if you could please help elaborate and share xml/code etc., as a comment. That would help me learn as well.

**Comment by krmahadevan** [comment]
@mfulton26 Never mind.. I understand what you said... :)
