### ISSUE TITLE
While installing Testng on eclipse-jee-juno-SR1-win32-x86_64 through help=>install new software got a problem 

### ISSUE THREAD

**Issue by rahulpise** [cbeust/testng#1060]
Attaching 1 snap and hoping to get the solution.
![testnginstallationproblem](https://cloud.githubusercontent.com/assets/10267117/15736699/1dc3066c-28bf-11e6-9356-a9ed60dc0efa.PNG)

**Comment by juherr** [comment]
Ping @missedone

**Comment by missedone** [comment]
hi @rahulpise 
according to the error message, there is missing [M2E](http://www.eclipse.org/m2e/) (Maven to Eclipse) plugins (or, version not satisfy the minimum required version 1.5) in your Juno package.
since 'TestNG M2E Integration' plugin is optional, so you can
1) either, install 'TestNG' plugin only, without 'TestNG M2E Integration' plugin
2) or, install the required M2E plugin in your Juno, if you want be benefit from the the m2e and testng m2e integration plugins
3), or, if it's possible, install the latest Eclipse bundle: [Mars.2](http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/mars2)

**Comment by juherr** [comment]
@rahulpise I think @missedone should fix your problem. Feel free to reopen the issue if it is still failing.
