### ISSUE TITLE
Webinar or HowTo for contributors

### ISSUE THREAD

**Issue by RocketRaccoon** [cbeust/testng#1109]
Hi,

Are you interesting in running some kind of webinar about TestNG architecture and development for those who would like to contribute in project?

**Comment by juherr** [comment]
Hi,

I'm not sure to understand what you propose, but any documentation that could help usage or development of TestNG are always welcome.
I think the best location to do it is in a [`CONTRIBUTING.md`](https://github.com/blog/1184-contributing-guidelines) file (feel free to propose something via a pull-request).
About architecture, the wiki could be a good place too.

Thanks for your help.

**Comment by sskorol** [comment]
I believe that @RocketRaccoon just asked main TestNG contributors (@cbeust and you @juherr) to provide a webinar, which explains TestNG core architecture for reducing an entry level to newbies, who is willing to become a committer. 

And to be honest it seems a bit strange to propose a newbie creating a PR with architecture details.

**Comment by RocketRaccoon** [comment]
@sskorol thanks for clarification, it's exactly that I wanted to say.

**Comment by juherr** [comment]
Ok, it is crystal clear now :)

The main source of internal documentation of TestNG is in @cbeust blog: https://www.google.com/?gws_rd=ssl#q=site:beust.com+testng and it is where I look for when I want to understand how/why something is working (or I disturb @cbeust :)).
The problem is TestNG is a 10 years old project with more/less activity in the last years; then the supposed architecture is not the actual one nor the one which should be in 2016 (and that's perfectly okay IMO).

About my experience, it often takes me a lot of time to find a fix for an issue because I don't know everything, and I have to rollback what I did when I understand the real cause.

In fact, if you want to contribute, go ahead and try something :) I always try to review pull-requests asap and help their authors to merge them.
For example, a good and easy start could be to review old pull-request (check if the problem still exists) and rework them (most of the time, a test is missing).
If you consider, like me, TestNG is a good project, and it should reborn, then feel free to propose any contributions, and I'll help you the best I can.

--------

> to be honest it seems a bit strange to propose a newbie creating a PR with architecture details

In the beginning, I didn't catch the question, and I agree with your point of view.
But I think too we could consider that a newbie is the best person who will be able to understand what a newbie need :)
