### ISSUE TITLE
Issue in org.testng.TestNG.generateReports method

### ISSUE THREAD

**Issue by Prakash-Saravanan** [cbeust/testng#1227]
```java
private void generateReports(List<ISuite> suiteRunners) {
    for (IReporter reporter : m_reporters) {
      try {
        long start = System.currentTimeMillis();
        reporter.generateReport(m_suites, suiteRunners, m_outputDir);
        Utils.log("TestNG", 2, "Time taken by " + reporter + ": "
            + (System.currentTimeMillis() - start) + " ms");
      }
      catch(Exception ex) {
        System.err.println("[TestNG] Reporter " + reporter + " failed");
        ex.printStackTrace(System.err);
      }
    }
  }
```

I am executing multiple Test classes. When I use `@Listeners(EmailableReporter.class)` at Test class level, this method invokes the reporter.generateReport as many times as the number of Test classes I have. The actual report with all the suites and test cases is generated at first invocation of the report itself.

Need to add a check to invoke generateReport method of an IReporter only once.

**Comment by juherr** [comment]
I'm not sure to understand the problem. Could you share a full sample I'll be able to run?

**Comment by krmahadevan** [comment]
@juherr - This issue is very easy to recreate.
Lets assume that I have two test classes that look like below :

```
@Listeners (EmailableReporter2.class)
public class Issue1227ClassOne {
    @Test
    public void testMethod() {
        System.err.println(getClass().getName() + ".testMethod() executed.");
    }
}
```

```
@Listeners (EmailableReporter2.class)
public class Issue1227ClassTwo {
    @Test
    public void testMethod() {
        System.err.println(getClass().getName() + ".testMethod() executed.");
    }
}
```
and I try to run both the above mentioned classes via a suite file such as below
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" parallel="false" verbose="2">
    <test name="Test">
        <classes>
            <class name="organized.chaos.forums.testng.Issue1227ClassOne"/>
            <class name="organized.chaos.forums.testng.Issue1227ClassTwo"/>
        </classes>
    </test> <!-- Test -->
</suite> <!-- Suite -->

```

The reason for this behavior is that TestNG ends up adding a new instance of `org.testng.reporters.EmailableReporter2` for every `@Listeners` annotation that it finds on each of the two classes. TestNG also ends up adding `EmailableReporter2` by default. So totally we have 3 instances of reporters. That explains the behavior being noticed by @Prakash-Saravanan

There are two ways of fixing this problem (IMO)

1.  Users should NOT inject default TestNG listeners (such as `org.testng.reporters.EmailableReporter2`) explicitly via `@Listeners` annotation or any other means. That way there won't be multiple instances of these default TestNG listeners.
2.  We have all of TestNG default listeners provide an implementation for `hashCode()` and `equals()` method, so that injecting instances into our `Set` of `IReporter` automatically takes care of unique instance addition. 

I am leaning towards (2) [ we can have all of TestNG default reporters extend an AbstractReporter which provides a consistent `equals()` and `hashCode()` behaviour]. Please let me know your thoughts.

**Comment by juherr** [comment]
Another solution could be to have a `Map<Class< ? extends IReporter>, IReporter>`.  Previously, I have already made similar things for some other listeners.

**Comment by krmahadevan** [comment]
@juherr - I did think about that too. I think I will go with the `Map` approach you suggested and raise a Pull Request for this as well.

**Comment by krmahadevan** [comment]
@juherr - I have tried fixing this issue. Can you please help take a look ?
