### ISSUE TITLE
supportsValidation(SAXParserFactory) method does not honor the value returned from SaxParserFactory.getFeature

### ISSUE THREAD

**Issue by jreisteter** [cbeust/testng#1292]
### TestNG Version
6.9.12

### Expected behavior
XMLParser<T> successfully instantiates a SAXParser with the correct setValidating argument.

### Actual behavior
A SAXParserFactory implementation that does not support validation may still have setValidating(true) invoked on it, causing an exception, leaving the SAXParser field uninitialized.

The root cause appears to be that the supportsValidation(SAXParserFactory) method does not honor the value returned from SaxParserFactory.getFeature, and instead always returns true if a call to getFeature does not throw an exception. The issue was caused in this [commit](https://github.com/cbeust/testng/commit/1cc0cfed393d8daaca96e848beccd3a6a13e6f06) as part of pull request #898 

### Is the issue reproductible on runner?
Reproduces when running TestNG on Android. The Android platform SAXParserFactory implementation does not support validation. Calling setValidating(true) causes an exception.

**Comment by krmahadevan** [comment]
Can you please add some instructions on how to reproduce this ? I am not familiar with Android that much but I would like to take a jab at this issue. How would I recreate this ? Any setups that need to be done ?

**Comment by juherr** [comment]
> the supportsValidation(SAXParserFactory) method does not honor the value returned from SaxParserFactory.getFeature, and instead always returns true if a call to getFeature does not throw an exception.

Yes. As I remember `SaxParserFactory.getFeature` always return `false` and the xml was never checked before. But maybe I'm doing it wrong and I didn't think about Android, for sure. :/
BTW, I'm open to another solution which is validating the xml.

**Comment by juherr** [comment]
I dug a bit and in fact, according to the documentation, [`SaxParserFactory#setValidating(boolean)`](http://docs.oracle.com/javase/8/docs/api/javax/xml/parsers/SAXParserFactory.html#setValidating-boolean-)  is not supposed to throw exceptions.
At the opposite, `SAXParserFactory#getFeature("http://xml.org/sax/features/validation")` is supposed to throw an exception if the parser doesn't know the feature.

For your information, [`SAXParserFactory#getFeature("http://xml.org/sax/features/validation")`](http://docs.oracle.com/javase/8/docs/api/javax/xml/parsers/SAXParserFactory.html#getFeature-java.lang.String-) and [`SAXParserFactory#isValidating()`](http://docs.oracle.com/javase/8/docs/api/javax/xml/parsers/SAXParserFactory.html#isValidating--) are supposed to produce the same result (except, `isValidating` doesn't throw exceptions): http://stackoverflow.com/questions/14853292/parser-setfeature-vs-parser-setvalidating

At the same time, [`SAXParserFactory#setValidating(true)`](http://docs.oracle.com/javase/8/docs/api/javax/xml/parsers/SAXParserFactory.html#setValidating-boolean-) is not supposed to throw an exception. In other words, we are not honoring `SaxParserFactory.getFeature` because it will always return `false` until we run `setValidating` or `setFeature`. So, we are already trying to catch specific parser behaviors by using `getFeature` and avoiding `setValidating` in the case of problems.

The documentation from Android is the same https://developer.android.com/reference/javax/xml/parsers/SAXParserFactory.html

Could you provide us more details on the android parser behavior because I really don't know what we can do more.

Feel free to reopen the issue in the case you think we can do something.
