### ISSUE TITLE
Beanshell based execution does not work any more

### ISSUE THREAD

**Issue by prvn133t** [cbeust/testng#1293]
### TestNG Version
6.10

### Expected behavior
Test cases inside the specified package should be executed successfully.

### Actual behavior
When beanshell is used in testng.xml to run the test cases inside the package, it does not execute any test cases. However not using the beanshell in testng.xml executes the test cases successfully.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="beanshellBugTestSuite" parallel="classes">
	<test name="beanshellbugtest">
		<method-selectors>
			<method-selector>
				<script language="beanshell">
                <![CDATA[packageName = System.getProperty("packageName");
                method.getDeclaringClass().getPackage().getName().contains(packageName);]]>
				</script>
			</method-selector>
		</method-selectors>
		<packages>
			<package name="com.testng.*" />
		</packages>
	</test>
</suite>
```

And I provide the packageName as -DpackageName=tests . So it should run all the tests inside the com.testng.tests package. But it does not run anything and the following is seen

```
===============================================
beanshellBugTestSuite
Total tests run: 0, Failures: 0, Skips: 0
===============================================

[BaseMessageSender] Received ACK:>ACK
[BaseMessageSender] Received ACK:>ACK
```

**Comment by krmahadevan** [comment]
Looks like this was broken between TestNG [6.9.13.7](https://bintray.com/cbeust/maven/testng/6.9.13.7) and TestNG [6.9.13.8](https://bintray.com/cbeust/maven/testng/6.9.13.8)

I will dig in deeper and see what I can find.

**Comment by krmahadevan** [comment]
@prvn133t - The issue is due to beanshell libraries missing.

Please add the below as a dependency and try again

```xml
<dependency>
    <groupId>org.beanshell</groupId>
    <artifactId>bsh</artifactId>
    <version>2.0b5</version>
</dependency>
```
After that, the beanshell execution should start happeneing.

[This](https://github.com/cbeust/testng/commit/fc7b27aac2156218fe5223561033fd762a5986ba) commit may be the root cause for this issue. I will see how to fix this.

**Comment by praveen133t** [comment]
@krmahadevan : Yes, including bsh as a dependency works. Thanks.

**Comment by cbeust** [comment]
Good catch @krmahadevan. Odd that we don't have a test for BeanShell, could you add one?

Thanks!

**Comment by juherr** [comment]
@krmahadevan @cbeust In fact the issue is there: https://github.com/cbeust/testng/commit/ff90ec521fb69d41e5c55cce1430440ae3594aeb#diff-9e9bc3b137c68b6d2f626cfa2a8545e5L61
Then the question is: should beanshell be a default or an optional dependency?
I prefer the optional option but it was a default dependency for a while.

**Comment by cbeust** [comment]
Yes, I remember now.

I guess optional is fine but then the BeanShell look up code should issue a useful error message if the BeanShell classes can't be found ("add a dependency to org.beanshell... to your build file in order to use BeanShell").

Thoughts?

**Comment by juherr** [comment]
Yes, sound good and easy: just have to add a log message in https://github.com/cbeust/testng/blob/5fa5ed7f9fb8428fbc2412321f95f73164222af7/src/main/java/org/testng/internal/BshMock.java#L8

**Comment by krmahadevan** [comment]
@juherr and @cbeust Shouldn't we instead be throwing an exception (`IllegalStateException` for e.g.,) if beanshell is not found in the classpath ? If a person is relying on beanshell for method selection, then I feel that we should throw an exception and let the user know that since the beanshell jars are not found in the classpath, their expected method selection via beanshell would not work ? Please let me know. based on that I can raise a PR.

**Comment by juherr** [comment]
@krmahadevan @cbeust +1 for an exception when a beanshell script is provided without the dependency.

**Comment by cbeust** [comment]
Yes, it should interrupt TestNG right there.

-- 
Cédric

**Comment by santoshkumar-soma** [comment]
Hi All,

I am facing similar issue with TestNg 6.10 Version. I have added the missing dependancy as well but not luck. I have tried with latest TestNg version but still Bean Shell selection is returning zero number of test methods.

<method-selectors>
      <method-selector>
        <script language="beanshell">
          <![CDATA[(groups.containsKey("P0") || groups.containsKey("P1"))]]>
        </script>
      </method-selector>
    </method-selectors>

Can you please help me.

**Comment by krmahadevan** [comment]
@santoshkumar-soma - You haven't provided enough information to help you get past your problem. I would request you to post details of your issue on the testng-users google forum (https://groups.google.com/forum/#!forum/testng-users). Please make sure you do the following

1. Upgrade to using the latest version of TestNG viz., 6.14.3
2. Share your beanshell expression along with a sample test that can be used to reproduce the problem.
