### ISSUE TITLE
jdk7 user getting compile error when use testNG 6.11

### ISSUE THREAD

**Issue by wentaliu** [cbeust/testng#1377]
### TestNG Version
6.11
### Expected behavior
TestNG should support jdk7 

### Actual behavior
JDK7 user getting Unsupported major.minor version 52.0  when compile their code that depends on testNG 6.11.

Java complaining about com.beust:jcommander:1.64, that is a jdk8 only lib after v1.58 (or so).

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@wentaliu - What happens when you exclude this version and switch over to using a previous version that works with JDK7 ? From [this](https://github.com/cbeust/testng/issues/1369) issue I understand that TestNG does not use any of the newly introduced APIs from JCommander. So I guess you should be good to work with an older version of JCommander.

**Comment by cbeust** [comment]
@wentaliu You are correct, this is a problem.

I just modified JCommander to compile to 1.7 and I uploaded it to JCenter (version 1.66). I also modified TestNG to depend on 1.66.

However, you won't benefit from this until the next version of TestNG, so if you are stuck with 1.7, I suggest you stay with the previous version of TestNG for now.
