### ISSUE TITLE
How to fail a test from onTestStart method

### ISSUE THREAD

**Issue by talgreen1** [cbeust/testng#1393]
### TestNG Version
6.11

### Expected behavior
I would like to be able to fail a test from the "**onTestStart**" method (of the TestListenerAdapter).
I tried to throw runtime exception or SkipException but the test always pass OK.
I also tried to set the test status by using this line:

`testContext.setStatus(ITestResult.FAILURE);`

### Actual behavior
The test passed OK.

### Is the issue reproductible on runner?

- Maven
- Eclipse
- IntelliJ

### Test case sample
```
public class TestManager extends TestListenerAdapter
{
	public void onTestStart(ITestResult testContext)
	{
		super.onTestStart(testContext);
		System.out.println("In onTestStart");
		testContext.setStatus(ITestResult.FAILURE);
		throw new RuntimeException("Trying to fail a test");
	}
}
```

**Comment by krmahadevan** [comment]
@talgreen1 

You can currently do this by throwing a `SkipException` from within an `IInvokedMethodListener` implementation.. Pls see if the below sample would work for you.

```java
package com.rationaleemotions.github.issue1393;

import org.testng.Assert;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;
import org.testng.SkipException;
import org.testng.TestListenerAdapter;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(SkipTestsDemo.TestManager.class)
public class SkipTestsDemo {
    @Test
    public void skipThisMethod() {
        Assert.fail("This method was not supposed to be executed");
    }

    @Test
    public void passme() {
        Assert.assertTrue(true, "Passing the test method");
    }

    public static class TestManager implements IInvokedMethodListener {

        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
            String name = testResult.getMethod().getMethodName();
            if ("skipthismethod".equalsIgnoreCase(name)) {
                throw new SkipException("Skipping the test method");
            }
        }

        @Override
        public void afterInvocation(IInvokedMethod method, ITestResult testResult) {

        }
    }
}
```

**Comment by talgreen1** [comment]
Thank you very much. It works.

**Comment by juherr** [comment]
@krmahadevan It looks like a workaround. Do you think we could improve something in TestNG?

**Comment by krmahadevan** [comment]
@juherr - Yes. We definitely can.

**Comment by bfurness** [comment]
I'm fairly sure this is actually a regression.   Back in the olden days of 6.9.13 throwing an exception in onTestStart would cause the test to fail as if the exception had occurred in the test itself.  As of 6.10 this was changed so that errors in onTestStart were seemingly silently ignored.  I did some digging and I think this is the culprit change
https://github.com/cbeust/testng/commit/50d534a100bfea002b9bcc8cfb97af6aea2a3ab6
now I can see why some people wouldn't want exceptions in methods such as onTestStart to cause issues, but they really could just wrap it in a try themselves.  That or people who do want the exception to be thrown need some other method they can use other then throw.  Either that or an option.

**Comment by svanvinge** [comment]
We make extensive use of listeners to manage test evaluation in runtime (e.g. if jira issue is open, skip test) and cannot upgrade because of this (if it is a regression). 

I have no problem remaining on 6.9.xx version, but it would be nice to know if it is indeed a regression or an intended change.  If it's a regression, I'll happily wait for a fix. If intended (it does make sense to handle skipping before invocation, even if it is more practical to use onTestStart), then using what @krmahadevan suggested as a permanent fix is fine.

**Comment by juherr** [comment]
@missedone What do you think?

**Comment by missedone** [comment]
I think we can revert the commit 50d534a

**Comment by missedone** [comment]
@juherr , @krmahadevan , I'm also thinking we might need a standard way allow user to fail the test in listener, for example, by throwing SkipException (or probably a new dedicate Exception for this purpose)

**Comment by krmahadevan** [comment]
@missedone - Instead of introducing a new exception what if we provided the ability to turn this `ON`/`OFF` via a configuration parameter ? That way for people who would like to see failures due to exceptions just need to turn this configuration parameter on and not have to do anything else. We could keep this configuration parameter value `OFF` by default.

**Comment by missedone** [comment]
@krmahadevan , I agree, it can be something similar as [ConfigFailurePolicy](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XmlSuite.java#L84)
