### ISSUE TITLE
Ability to pass different number of parameters to the same test case using data provider

### ISSUE THREAD

**Issue by prasanta-biswas** [cbeust/testng#1449]
For details please visit the stackoverflow link [here](https://stackoverflow.com/questions/44480509/is-it-possible-to-pass-dynamic-number-of-parameters-to-same-testng-test-with-sam).

**Comment by krmahadevan** [comment]
@prasanta-biswas - Re-iterating your question. You would like TestNG to start being agnostic with the parameters length when dealing with data driven test methods i.e., TestNG should ignore the number of parameters that are to be expected by a data driven test method, and forcibly try to bind the `@Test` method with its `dataprovider`.

Please refer to the answers to your question.

IMHO, this is not a use case that maybe addressed by TestNG. You would need to adopt one of the following approaches (all of them have been provided as answers to your stack overflow question)

* Inspect the `Method` object that TestNG injects into the `@DataProvider` annotated method and based on it, toggle between the data to be sent back.
* Wrap your parameters inside a custom Object and then extract out values from within it.
* Have your `@Test` method just accept a generic `Object` and then run `instanceof` checks on the parameter to decide what should be the expected behavior.

**Comment by juherr** [comment]
I'm not sure to understand the need but as suggested on SO, you can wrap the parameter logic into interfaces/objects.

**Comment by prasanta-biswas** [comment]
I thought this could be a great feature in terms of reusability.

**Comment by krmahadevan** [comment]
@prasanta-biswas - Yes I hear you and understand the intent. Its just that, this is already possible currently in TestNG without the TestNG codebase going through any changes, if you follow one of the options that were called out in StackOverFlow as answers to your question. I hope that answers your question and you can close this issue.

**Comment by prasanta-biswas** [comment]
yes as a workaround your answer there solves it.

**Comment by juherr** [comment]
What values should TestNG put when the data provider doesn't provide them? And why don't your data provider providing all parameters of the method?

```java
@DataProvider(name="dp")
public Object[][] dp(Method m) {
  Class<?>[] params = m.getParameterTypes();
  // return appropriate values according `params`
}
```

**Comment by krmahadevan** [comment]
@juherr - We can close this issue I guess.

**Comment by juherr** [comment]
@prasanta-biswas Your use case looks too specific to be integrated into TestNG and you have workarounds to do it, then I close the issue.
But thanks for the idea and feel free to propose things if you think it could be interesting for others :)
