### ISSUE TITLE
How to call IAnnotationTransformer in comand line after version6.10(or6.11)

### ISSUE THREAD

**Issue by zutuanwang** [cbeust/testng#1450]
### TestNG Version
> 6.10(or6.11)

### Expected behavior
call IAnnotationTransformer in comand line

### Actual behavior
```java
TestNG tng = new TestNG();
tng.setAnnotationTransformer(gtf);
// has removed after6.10
//and when I use testng6.9, it seens that don't task effect in jdk1.8.0.31
```

**Comment by juherr** [comment]
When you say CLI, you mean "by code", rigth?

And I don't understand your issue because `setAnnotationTransformer` is just deprecated, not removed.

According to the javadoc:
> void setAnnotationTransformer(IAnnotationTransformer t)
> Deprecated. 
> Use addListener(ITestNGListener) instead

https://jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/TestNG.html#setAnnotationTransformer-org.testng.IAnnotationTransformer-

**Comment by krmahadevan** [comment]
@juherr - Should we be closing this issue ?
