### ISSUE TITLE
Possibility to retry a test until it FAILED

### ISSUE THREAD

**Issue by kateleiza** [cbeust/testng#1519]
We need to have a possibility to run tests until test will be failed (because we have flaky tests and want to run a test until it failed and then investigate: read logs etc) 

Main problem: hardcoded FAILURE test status in condition for retry: 
```java
boolean willRetry = retryAnalyzer != null && status == ITestResult.FAILURE && failure.instances != null && retryAnalyzer.retry(testResult);
```

In old TestNG version (TestNG which bundled with IDEA) we had a chance to avoid it by the following way:

```java
class RetryUntilFailedListener : IInvokedMethodListener {
    override fun beforeInvocation(method: IInvokedMethod?, testResult: ITestResult?) { }

    override fun afterInvocation(method: IInvokedMethod?, testResult: ITestResult?) {
        if (method!!.isTestMethod) {
            if (testResult!!.status == ITestResult.SUCCESS) {
                println("SUCCESS. NEED TO RETRY")
                testResult.status = ITestResult.FAILURE //because retry works only if (testResult.getStatus() == ITestResult.FAILURE)
                testResult.setAttribute("RETRY", "YES")
            } else if (testResult.status == ITestResult.FAILURE)
                testResult.setAttribute("RETRY", "NO")
        }
    }

}
```

but now it doesn't work because in old versions  `invokeTestMethods` run `handleInvocationResults` but now it doesn't. So now I can't override test status before retry logic.

### TestNG Version
latest

**Comment by krmahadevan** [comment]
@kateleiza - Can you please help add a sample that can be executed to reproduce the problem ? I am not able to completely understand what the problem is, reading the description shared.

**Comment by kateleiza** [comment]
@krmahadevan Hi! The problem is that I can't use retry logic (IRetryAnalyzer) for SUCCESS tests

**Comment by krmahadevan** [comment]
@kateleiza 

> The problem is that I can't use retry logic (IRetryAnalyzer) for SUCCESS tests

Its entirely not clear or obvious to me as to why would you expect a retry logic to try running a test that has passed already. If you would like to control the outcome of a test, that has passed, perhaps you might want to have it executed via a `IHookable` interface implementation, wherein TestNG lets you control what happens before and after a test method is executed (which is not necessarily a `@BeforeMethod` and `@AfterMethod` equivalent).

Like I said, the problem statement is not clear, which is why I ask that you please help share a sample that can be used to reproduce the problem and also include version numbers of TestNG wherein you found this to work earlier. That would help us figure out where to troubleshoot.

**Comment by kateleiza** [comment]
[Test.zip](https://github.com/cbeust/testng/files/1266867/Test.zip)
here is a sample project which now doesn't work

**Comment by krmahadevan** [comment]
@kateleiza - And what was the version in which it used to work ?

**Comment by kateleiza** [comment]
6.0

**Comment by kateleiza** [comment]
Thank you very much!

**Comment by kateleiza** [comment]
@krmahadevan I try and, unfortunately, it doesn't work for me. Because I need to change `testResult.status` from SUCCESS to FAILURE in `RetryUntilFailedListener.afterInvocation()` (please see the code above), but `handleInvocationResults()` gets status from `holder.status` which is SUCCESS, so `status == ITestResult.FAILURE` condition is false

**Comment by juherr** [comment]
@kateleiza Could you open a new issue?

**Comment by kateleiza** [comment]
Sure. https://github.com/cbeust/testng/issues/1600
