### ISSUE TITLE
Run failed tests using RetryAnalyzer after the complete of the suite

### ISSUE THREAD

**Issue by hemanthsridhar** [cbeust/testng#1532]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Want an option to run the failed tests after the 1 round of suite execution.

### Actual behavior
Currently RetryAnalyzer implementation reruns the failed test case immediately after a test case fails.

### Is the issue reproductible on runner? Yes

- [x] Maven

**Comment by juherr** [comment]
The feature already exists: http://testng.org/doc/documentation-main.html#rerunning

**Comment by hemanthsridhar** [comment]
@juherr can you please guide specifically on how to run the failed tests after the 1 complete round of suite execution.

**Comment by hemanthsridhar** [comment]
@juherr
 *I want to achieve this automatically *

**Comment by krmahadevan** [comment]
@hemanthsridhar - I would like to understand what do you gain by waiting for TestNG to first run all the tests, and then after an entire execution is done, then have TestNG run only the failed tests.

How is it different from using a `RetryAnalyzer` and having TestNG retry a Test immediately when there's a failure.

> Can you please guide specifically on how to run the failed tests after the 1 complete round of suite execution.

Now that TestNG does provide you with `testng-failed.xml`, for you to be able to do this via Maven, here's what I can think of 

1. Create your own TestRunner class (One that makes use of TestNG APIs and has a `main()` method exposed wherein you can basically build the logic of Having TestNG run with the `testng-failed.xml` if it exists. Something like the below skeleton

```java
public static void main(String[] args) throws IOException {
    TestNG testng = new TestNG();
    testng.setXmlSuites(createSuites());
    testng.setVerbose(2);
    testng.run();
}
```

2. You can now invoke your custom TestRunner class by using the [Exec Maven Plugin](http://www.mojohaus.org/exec-maven-plugin/java-mojo.html). You can have this plugin execution piggy back the surefire plugin execution 

But this approach is going to have a lot of problems.

- First you would need to figure out how to collate both the test results (The test results from the surefire plugin + the test results from running the `testng-failed.xml`)
- You also need to figure out a way in which you can fail the build. By default surefire plugin fails the build if there are test failures, but since now you will be retrying them via your exec plugin task, you should disable that and then have the exec plugin fail the build.
