### ISSUE TITLE
groups execution - beforeGroups()

### ISSUE THREAD

**Issue by khmarbaise** [cbeust/testng#157]
I have a project which has some groups in there but when i execute this example the beforeGroups method is not executed at all....Furhtermore i have defined an order of the groups in the testng.xml file which seemed to be ignored ?...Maybe i'm doing something wrong...

Here is the link to the Maven based project:

http://blog.soebes.de//uploads/testng-problem.zip

**Comment by krmahadevan** [comment]
@khmarbaise - The github project that is shared doesn't seem to contain any `@BeforeGroups` annotated method. I also dont see any `testing.xml` which is filtering by groups. TestNG will execute `@BeforeGroups` only if the execution is filtering based on groups.

I am closing this issue. If this is still a problem, please help do the following

1. Upgrade to the latest released version of TestNG viz., `7.0.0-beta1` as of today and retry the issue.
2. If the problem persists, please help share a sample project which can be used to reproduce the issue, along with some expected output, so that we can dig deeper and find out what is going wrong.
