### ISSUE TITLE
Running TestNG programmatically with maven

### ISSUE THREAD

**Issue by felipenazario** [cbeust/testng#1576]
### TestNG Version
> version 6.11

Hi, I'm trying to running TestNG programmatically and call it by maven using surefire plugin, how can I make it work?.

### Java

```java
// this code works on eclipse running as a Java Application
public class TesteModeloMain {
    public static void main(final String[] args) throws Exception {
        final TestNG testng = new TestNG();
        testng.setTestClasses(this.getClasses());
        testng.addListener(new ListenerErrorClass());
        testng.setOutputDirectory("target/test-output/");
        testng.setParallel(XmlSuite.ParallelMode.TESTS);

        testng.run();
        System.exit(0);
    }
}
```

### Maven
```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.20.1</version>
            <configuration>
                <includes>
                    <!-- It's found, but not executed -->
                    <include>br.org.igreja.teste.base.TesteModeloMain</include>
                </includes>
            </configuration>
        </plugin>
    </plugins>
</build>
```

**Comment by felipenazario** [comment]
TesteModeloMain it is at src/test/java/

**Comment by krmahadevan** [comment]
I don't think the Maven surefire plugin is capable of running `main()` methods.
`<includes>` lets surefire plugin know what sort of Java classes to look for, which explains how your class got found by surefire plugin. See [here](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes) for more details.

 The surefire plugin has providers within itself which starts off the execution wherein it instantiates a `TestNG` object and then runs its `run()` method [ this internally looks for TestNG annotated methods ]. You would need to be using the `maven-exec-plugin` for doing this. Please refer [here](http://www.mojohaus.org/exec-maven-plugin/java-mojo.html) for more information. 

I am closing this issue, since its not related to TestNG.
