### ISSUE TITLE
Updated in afterInvocation() testResult.status is not used in willRetry condition

### ISSUE THREAD

**Issue by kateleiza** [cbeust/testng#1600]
### TestNG Version
latest

### Expected behavior
when I change `testResult.status` in `MyListenter.afterInvocation()` it should be used in willRetry condition. So when I change `testResult.status` from SUCCESS to FAILURE, RetryAnalyser should be invoked.

more details in https://github.com/cbeust/testng/issues/1519
### Actual behavior
RetryAnalyser is not invoked.

### Test case sample
[Test.zip](https://github.com/cbeust/testng/files/1453984/Test.zip)

**Comment by krmahadevan** [comment]
@kateleiza - I don't think there's any problem with TestNG here. The issue is in your test code.

You are using a listener which looks like below 

```java
public class MyListener implements IInvokedMethodListener, IAnnotationTransformer {
...
}
```
wherein you are adding the retry analyzer via the `transform()` method

You are injecting this listener into your test class via the `@Listeners`.

TestNG does not let you inject `org.testng.IAnnotationTransformer` implementations via `@Listeners` annotation. You need to add this listener only via one of the below ways : 

1.  using the `<listeners>` tag in your suite xml file.
2. Using [SPI](https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html). For details on how to use an SPI approach to inject listeners, refer to the [TestNG documentation](http://testng.org/doc/documentation-main.html#listeners-service-loader)

Lastly here's a suite xml that I created for the test suite you shared and ran it

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1600_suite" parallel="false" verbose="2">
    <listeners>
        <listener class-name="rationale.emotions.github1600.MyListener"/>
    </listeners>
    <test name="1600_test">
        <classes>
            <class name="rationale.emotions.github1600.MyTest"/>
        </classes>
    </test>
</suite>
```

The output 

```
...
... TestNG DEV-SNAPSHOT by Cédric Beust (cedric@beust.com)
...
SUCCESS. NEED TO RETRYPASSED: test1

===============================================
    1600_test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

===============================================
1600_suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

**Comment by kateleiza** [comment]
@krmahadevan `SUCCESS. NEED TO RETRY`
and then it should be retried. But there is only `Total tests run: 1` - but should be 1 failed and 1 passed

**Comment by krmahadevan** [comment]
@kateleiza - Thanks for pointing it out. I have re-opened the issue and I see the problem section as well. But I would like to correct your understanding.

>  but should be 1 failed and 1 passed

This is not true. In your case, it would only be `1 failed and 1 skipped` because all attempts until no more retry is required, are all considered as `skips` by TestNG

**Comment by kateleiza** [comment]
@kamilszymanski Yes, thanks. 1 failed and 1 skipped, exactly
