### ISSUE TITLE
Support XPP Parser

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1643]
From: https://stackoverflow.com/q/47803408/4234729

### TestNG Version
6.13

### Expected behavior
Should not fail and try to parse the xml without validation.

### Actual behavior
```
[testng] javax.xml.parsers.ParserConfigurationException: validation is not supported
[testng]    at org.gjt.xpp.jaxp11.SAXParserFactoryImpl.newSAXParser(SAXParserFactoryImpl.java:100)
[testng]    at org.testng.xml.XMLParser.<clinit>(XMLParser.java:29)
[testng]    at org.testng.xml.Parser.<clinit>(Parser.java:34)
[testng]    at org.testng.TestNG.parseSuite(TestNG.java:290)
[testng]    at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:334)
[testng]    at org.testng.TestNG.initializeEverything(TestNG.java:974)
[testng]    at org.testng.TestNG.run(TestNG.java:988)
[testng]    at org.testng.TestNG.privateMain(TestNG.java:1330)
[testng]    at org.testng.TestNG.main(TestNG.java:1299)
[testng] [TestNG] [ERROR] java.lang.NullPointerException
[testng] Exception in thread "main" java.lang.NullPointerException
[testng]    at org.testng.TestNG.getStatus(TestNG.java:206)
[testng]    at org.testng.TestNG.main(TestNG.java:1300)
[testng] The tests failed.
```

### Test case sample
Use https://www.extreme.indiana.edu/xgws/xsoap/xpp/ and find appropriate tweak for https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XMLParser.java#L61-L69

**Comment by krmahadevan** [comment]
@juherr - I am not sure if this still needs to be fixed. Per the user, in the same stackoverflow post, the issue got resolved when the user moved over to using a newer variant of this parser. So I guess there's nothing needed from our side. WDYT ?

**Comment by juherr** [comment]
@krmahadevan Your solution is a good workaround but the code is supposed to work with any `SAXParser` implementation, especially `supportsValidation` which should return false with XPP.

**Comment by krmahadevan** [comment]
@juherr - I believe the problem was with the version of the parser being used by the OP. When the OP moved over to using the latest version of the XPP parser, the issue got resolved. Please see the OP's comments [here](https://stackoverflow.com/questions/47803408/why-is-testng-throwing-a-javax-xml-parsers-parserconfigurationexception-valida/47805318?noredirect=1#comment82609650_47805318)

**Comment by juherr** [comment]
@krmahadevan As I understand it, he updated a dependency and XPP was removed from the classpath. I'm not sure XPP is working. I'd like to make a test before closing the issue.

**Comment by krmahadevan** [comment]
@juherr - Sure. But here's my theory.  We basically have [this](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/xml/XMLParser.java#L61-L69) mechanism within TestNG to determine if a parser supports validation or not. I am not an expert on xml parsers, but just wondering. Shouldn't it be the responsibility of the parser to basically return a proper value when TestNG attempts to determine if the parser supports validation or not ? Because the error is stemming from the actual parser and not from TestNG. WDYT ?

**Comment by juherr** [comment]
Yes, the mechanism should work but I'd like to check why it is not working in that specific case.

At the same time, the library is so old we can drop the support :)
