### ISSUE TITLE
parallel="classes"  Tests not running in parallel mode with gradle

### ISSUE THREAD

**Issue by pgsung** [cbeust/testng#1701]
### TestNG Version
> Note: only the latest version is supported
6.14.2
### Expected behavior
Tests should run in the parallel mode with gradle 4.3.1 with testng.xml at https://github.com/pgsung/testng-bug/blob/master/src/test/resources/testng.xml
and source code at https://github.com/pgsung/testng-bug
test classes https://github.com/pgsung/testng-bug/tree/master/src/test/java/parallel/test
, thread ids should be different. 

```
[RemoteTestNG] detected TestNG version 6.14.2
11
12
10
```

===============================================
content-backoffice-ci-uitest Suite
Total tests run: 3, Failures: 0, Skips: 0

### Actual behavior
Tests not running in parallel mode with gradle 4.3.1

```
content-backoffice-ci-uitest Suite > thread-test > parallel.test.Test1.runTests STANDARD_OUT
    10
Running test: Test method runTests(parallel.test.Test2)

content-backoffice-ci-uitest Suite > thread-test > parallel.test.Test2.runTests STANDARD_OUT
    10
Running test: Test method runTests(parallel.test.Test3)

content-backoffice-ci-uitest Suite > thread-test > parallel.test.Test3.runTests STANDARD_OUT
    10
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [X] Gradle (same behavior with gradle 4.5.1)
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

Eclipse runner version   TestNG	6.13.0.201712040650 is actually running fine.

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

1. clone the repo at https://github.com/pgsung/testng-bug
2. run the test with command ./gradlew clean test

Workaround: switch back to 6.11

**Comment by krmahadevan** [comment]
This seems to be an issue with Gradle. I am not that well versed with Gradle. But my debugging seems to suggest that when we hit the flow [here](https://github.com/gradle/gradle/blob/v4.3.1/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java#L94-L130) the parallel mode is getting reset back to null. This issue has been fixed in TestNG as of 6.14.2. You can try right clicking on your testng.xml suite file in your project and running it. You should see different thread ids. 

To get past this in gradle as well, just add the parallel mode to your `<test>` tag as well and try again. You should be fine.

@juherr - Any idea on how to get this sorted out in gradle ? Should we ask @pgsung to raise a bug against gradle and follow it up there, while we close this issue here ?

**Comment by juherr** [comment]
I think the gradle issue tracker will be a better location.

**Comment by krmahadevan** [comment]
@pgsung - Please raise an issue [here](https://github.com/gradle/gradle/issues) to get this addressed. Closing this off, since TestNG doesn't seem to be cause of the problem.

**Comment by pgsung** [comment]
Thank you guys. Filed the issue to gradle at https://github.com/gradle/gradle/issues/4457
