### ISSUE TITLE
Customize testng-results.xml

### ISSUE THREAD

**Issue by hontrang** [cbeust/testng#1721]
Hi folks,
I created file run.bat to execute 3 testng xml files look like:
`java -cp "bin;lib\*" org.testng.TestNG testng_chrome_jp.xml`
`java -cp "bin;lib\*" org.testng.TestNG testng_chrome_cn.xml`
`java -cp "bin;lib\*" org.testng.TestNG testng_chrome_asia.xml`

Normally, testng-results.xml in folder test-output will show report of suite testng_chrome_asia.xml because it will override previous report.
What i expected to combine the result of the whole suites to just a testng-results.xml file. Any way to do that please give me your advice.
Thanks

**Comment by krmahadevan** [comment]
You need to do the following (But make sure you are working with the latest released version which is `6.14.3` as of today)

Pass the report name via the JVM argument `-Dtestng.report.xml.name` in each of the `java -cp` commands so that they are unique in each of the cases.

You then merge the xml into one. Here's [one](https://stackoverflow.com/q/9004135) way of doing it.
