### ISSUE TITLE
Failure in before* leads to test skip in case of data driven testing

### ISSUE THREAD

**Issue by vinaybalepur** [cbeust/testng#1755]
### TestNG Version
> Version - 6.14.2

### Expected behavior
> If configuration methods before* fails then test cases should not be skipped. 

### Actual behavior
> The test cases are skipped and are not executed. This is observed even when configfailurepolicy="continue" is set in the xml file. Attaching the xml file as well.
[TestDepends.txt](https://github.com/cbeust/testng/files/1890197/TestDepends.txt)
[Testxml.txt](https://github.com/cbeust/testng/files/1890199/Testxml.txt)

configfailurepolicy | skip\|continue | **Whether TestNG should continue to execute the remaining tests in the suite or skip them if an @Before\* fails. Default behavior is skip.**
-- | -- | --

### Is the issue reproductible on runner?

- [ ] Shell
- [ #] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
      Has been shared

**Comment by krmahadevan** [comment]
@vinaybalepur - Didn't I explain the behavior of TestNG in detail as part of your earlier issue in this comment : https://github.com/cbeust/testng/issues/1754#issuecomment-379843609

TestNG cannot retry a `@BeforeClass` method because its executed only once per class. Your data driven `@Test` methods get executed multiple times for the same class. Imagine the `@BeforeClass` to be something like a constructor for your class. Just as Java doesn't invoke it multiple times but only once at the time of object creation, TestNG also invokes `@BeforeClass` once per class. You should be leveraging a `@BeforeMethod` to get what you are looking for.

I believe I have shared an elaborate and fully functioning sample in my comment.

What additional info are you expecting here ? Care to elaborate ?

**Comment by vinaybalepur** [comment]
I could not reopen the ticket and have left a comment there already. If you look at this ticket the documentation says the configfailurepolicy="continue" is set to true then even if any configuration method fails the test should continue execution. Either doc is wrong or my understanding. Please do clarify.

**Comment by krmahadevan** [comment]
@vinaybalepur - Please go back to the original issue and review again. I have answered your question to the best of my abilities (my comment is the last there).

Please go through what I have logged in there as a finding and then let me know if it still doesn't answer your question.

cc @juherr - Please help add in case I am missing anything.

**Comment by krmahadevan** [comment]
No response from the user. Closing the issue.
