### ISSUE TITLE
Add "default" keyword would introduce backward compatibility issues

### ISSUE THREAD

**Issue by eyehwan** [cbeust/testng#1764]
### TestNG Version
Since "Fixed: GITHUB-1759: core interfaces refactoring to support default methods"

### Expected behavior
TestNG is supposed to be invoked by Eclipse. 
Please re-consider about introducing keyword "default" from Java 8 to TestNG before taking control of 
backward compatibility issues.

### Actual behavior
[RemoteTestNG] detected TestNG version 7.0.0
java.lang.NoSuchMethodError: org.testng.remote.AbstractRemoteTestNG.addListener(Lorg/testng/ISuiteListener;)V
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans
For the others, not tested yet. 

### RootCause:
From https://github.com/testng-team/testng-remote/blob/master/remote/src/main/java/org/testng/remote/AbstractRemoteTestNG.java 
```
  private static class RemoteSuiteListener implements ISuiteListener {
    private final MessageHub m_messageSender;

    RemoteSuiteListener(MessageHub smsh) {
      m_messageSender= smsh;
    }

    @Override
    public void onFinish(ISuite suite) {
      m_messageSender.sendMessage(new SuiteMessage(suite, false /*start*/));
    }

    @Override
    public void onStart(ISuite suite) {
      m_messageSender.sendMessage(new SuiteMessage(suite, true /*start*/));
    }
  }
```

**Comment by krmahadevan** [comment]
@eyehwan - I am not sure I quite understand the issue here. Can you please explain it one more time? With `TestNG 7.0.0`, we have moved towards using `JDK8`. So the codebase is going to go through with changes to adopt the JDK8 features. Why does it have to be backward compatible ?

Are you talking about the compatibility between the TestNG eclipse plugin that @missedone helps take care of, with TestNG ? If yes, then I am not sure, if the TestNG eclipse plugin has been enhanced to be compatible with `TestNG 7.0.0` (I think @missedone usually does this only after TestNG 7.0.0 has been released)

**Comment by missedone** [comment]
the testng eclipse plugin does not yet support testng 7.0.0
as i think there will be more breaking changes, i plan to do it when comes to RC stage.

**Comment by krmahadevan** [comment]
Closing this issue.
