### ISSUE TITLE
[Question] If i create a extension and i want submit a pull request, does it support for kotlin

### ISSUE THREAD

**Issue by phoenix-young** [cbeust/testng#1768]
Hi there,

I just create a testng extension here https://github.com/phoenix-young/ApiTest/blob/master/readme.md.

My question is:
1. My project is build by kotlin, if i want to send the pull request to testng, does it support for kotlin?

**Comment by krmahadevan** [comment]
@phoenix-young - If its a changeset that is supposed to be part of the TestNG codebase, then the changeset has to be in Java and not Kotlin. 

Maybe you could enrich the project's `README.md` with details on how to consume a Kotlin project as dependency in a Maven project ( something like [this](https://turreta.com/2017/05/26/kotlin-how-to-use-your-kotlin-library-in-java-maven-projects/) ) and then raise a PR against the [TestNG documentation repository](https://github.com/testng-team/testng-team.github.io) so that there's an entry into your extension project in the [misc](http://testng.org/doc/misc.html) section.

@juherr @cbeust Your thoughts ?

**Comment by juherr** [comment]
@phoenix-young As @krmahadevan said, the main language of TestNG is currently Java and we don't plan to change it for the moment.
So, if you want to share some improvement, you'll have to do it in Java only. But as Kotlin is compatible with Java, it should not be a big deal for your extension.
