### ISSUE TITLE
using 2 Before method and after methods in selenium testNG

### ISSUE THREAD

**Issue by pradeepsai11** [cbeust/testng#1792]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@pradeepsai11 - What is the issue ? Please try using the latest released version of TestNG viz., `6.14.3`
 What version have you been working with ? Can you please add a sample test (please keep it simple without any external dependency such as selenium etc.,) that can be executed to reproduce the issue.

**Comment by pradeepsai11** [comment]
using the 6.14.0  TestNG version....is it not compatible?
Issue:  Am using the @Beforeclass, @BeforeMethod, @Afterclass, @AfterMethod, @Test1,@Test2 in testNG
But the issue is I need to login the mms1 credentials for 1st testcase and after loggingout I need to login to mms2 credentials for 2nd testcase....Here it is pointing to mms1 alone due to am using BeforeMethod and AfterMethod...any possibility for doing above scenario??

**Comment by krmahadevan** [comment]
@pradeepsai11 - I am re-iterating again. Please do the following :

1. First try reproducing the problem using the latest released version of TestNG `6.14.3`.
2. If you are able to reproduce the issue, please add a simple test that we can run to reproduce the problem. What you have shared so far, doesn't help a lot in even trying to figure out what could be the root cause of the problem.

**Comment by pradeepsai11** [comment]
@beforeclass
@beforemethod
@afterclass
@aftermethod
@Test(priority=1)
public void leadcreate()
@Test(priority=2)
public void leadApprove()


in above code,@beforemethod I need to login as username1 for @Test1 i.e leadcreate(), then after logout,username2 I need to login for @Test2 i.e leadApprove()

is there such possibility using TestNG annotations?

**Comment by krmahadevan** [comment]
Can you please give a concrete example that shows what you are expecting?
What you have shared, does not make a lot of sense, because you seem to
have one method cater to multiple annotations (Not sure what you are trying
to accomplish with that). If all you need is a "@BeforeMethod", then why do
you need to annotate the method using "@BeforeClass". Your use case is not
clear.

**Comment by krmahadevan** [comment]
No response from the user. Please help share a standalone test as requested above, if this is still a problem (using TestNG `v6.14.3`)
