### ISSUE TITLE
Snapshot not updated

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1804]
From https://github.com/cbeust/testng/pull/1783#issuecomment-390488574

**Comment by ryudice** [comment]
Hi, is there any otherway to get a snapshot build?

**Comment by krmahadevan** [comment]
ping @cbeust - Can you please help with getting this sorted out ?

**Comment by cbeust** [comment]
Can't really right now, but these snapshots should be automatically uploaded directly from Travis, shouldn't they? Maybe you or Julien can call this task manually and see what happens?

**Comment by krmahadevan** [comment]
@cbeust - I have raised a PR for this.

I think the root cause was that we are having a check in the `publish` task of `travis.sh` which gets called post build, which checks if the current JDK on the travis build machine is JDK7 and publishes only if this criteria is met. But ever since moved to JDK8, I guess the publishing has not been happening.

Here's what the looks like

```
[32;1muploading archive[0m

travis_time:end:0fb7d5ae:start=1528307284048913144,finish=1528307300189803348,duration=16140890204
[0Ktravis_fold:end:cache.2
[0Ktravis_fold:start:after_success.1
[0Ktravis_time:start:35ed7880
[0K$ ./travis.sh deploy
Deploy skipped: Only on Oracle JDK7
```

**Comment by krmahadevan** [comment]
Finally we are back to publishing snapshots on maven central.
testng-7.0.0-20180608.033742-2.jar (https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/7.0.0-SNAPSHOT/testng-7.0.0-20180608.033742-2.jar) 


```

**Comment by cbeust** [comment]
Thanks for fixing it, Krishnan!

-- 
Cédric


On Thu, Jun 7, 2018 at 8:46 PM, Krishnan Mahadevan <notifications@github.com
