### ISSUE TITLE
Support the Junit 5 TestEngine API

### ISSUE THREAD

**Issue by thejeff77** [cbeust/testng#1845]
*Feature Request*

### TestNG Version
> Note: only the latest version is supported

### Expected behavior
> Supportes the Junit 5 TestEngine API

### Actual behavior
> Does not seem to support this API

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@cbeust @juherr - Just curious behind the use case of why TestNG supports JUnit executions. Traditionally I can understand that it was one of the ways of paving way for people to migrate or adopt TestNG without them having to do changes to their existing JUnit tests. But is that still the use-case here, especially after the fact that TestNG has already been out there for over 10 years and JUnit 5 (from what I understand) has similar features to what TestNG has.

@thejeff77 - Please feel free to chime in and add context. This is just to help me understand the context a bit better, as to when you would want to use TestNG to run JUnit5 tests. JUnit 5 is relatively new. So I am guessing that those scripts must be newly created as well. So why wasn't TestNG directly used, instead of having them written in JUnit5 and then needing TestNG to run them. What purpose does this execution model solve ?

**Comment by juherr** [comment]
In fact, the junit support allows mixed suite with JUnit and TestNG tests. It's not so often but I've already noticed issues on Maven Surefire where the user has such kind of suites.

The feature request here is just having a testng-engine as described on https://blog.codefx.org/design/architecture/junit-5-architecture/#Architecture
It will allow an easier maintenance for 3rd parties like build tools or IDE plugins because they will only have to manage one single api.
I've already tried an implementation months ago but the api and some concepts were not so easy to understand. BTW, it could be a fun project if you want to learn a lot about JUnit and TestNG.

**Comment by thejeff77** [comment]
@krmahadevan Thank you for your timely response. This is all about support and integration. Our company is looking at starting to write tests again, and all of our old tests are in Junit 4. TestNG looks awesome, but it is hard to make the case to use it if we'd have to convert all old tests to testng. As you may or may not know, Junit 5 is backwards compatible, and includes the Junit Vintage jar which is capable of running older versions of junit tests such as ours. If testng supported the TestEngine API, it would be a powerful factor in allowing companies such as ours to start writing tests in TestNG without the overhead of worrying about a full blown conversion. Especially since a major goal in JUnit 5 was creating the ability to integrate with other frameworks (TestEngine API), it would be a major case for the second most-used java test framework (TestNG) to allow seamless integration and simultaneous use alongside the most recognized name in java test frameworks (Junit 5). Currently, for anyone who used Junit in the past - using Junit 5 is a no-brainer due to its integration potential and backwards compatibility, and is likely why we'll use this one. As @juherr and others online have outlined - it is not as straightforward as desired to use the two in parallel, making it hard to justify the TestNG framework for a project that has previously written tests in Junit. The unknowns and potential time sink of dealing with issues running TestNG is a productivity risk for us to use this framework.

**Comment by juherr** [comment]
@thejeff77 Did you notice that TestNG supports JUnit 4 too? It means you will be able to write you new tests with the TestNG API and keep your previous tests with JUnit 4 without having to modify them.

**Comment by atulagrawal** [comment]
@juherr - I went through the article and i liked the idea very much. Please let me know if there is any opportunity for collaboration.

**Comment by juherr** [comment]
@atulagrawal In fact, it depends on you first. Feel free to work on it because you need to understand the JUnit5 and TestNG api first and then find a way to link them.
If needed, we can help you on a dedicated issue on github.

**Comment by atulagrawal** [comment]
Ok. Let me go through the APIs first. I don't have any experience with JUnit 5 so may be i will play around with it for a while to understand the concepts.

**Comment by sormuras** [comment]
I'm also interested in helping to provide a `TestNGine`, i.e. an implementation of the JUnit Platform `TestEngine` interface that knows _what_ TestNG tests are and _how_ to execute TestNG tests.

I do understand the JUnit Platform API but only skimmed the TestNG API so far. So, perhaps, I'll start a spike and share the skeleton implementation here for fleshing it out.

**Comment by juherr** [comment]
@sormuras I'd love to help even if I don't have a lot of time. The skeleton will help because I didn't understand the API months ago.

BTW, I created a dedicated repository: https://github.com/testng-team/testng-junit5
I can give you write access if needed.

**Comment by sormuras** [comment]
Sure. Let's get started over there.

**Comment by sormuras** [comment]
> Can we get this to start using JDK8 ?

Aye. Will finish the spike first, then get https://github.com/sormuras/junit-platform-maven-plugin compile to JDK 1.8 bytecode (mrjar), and then use `--release 1.8` here as well.

**Comment by sormuras** [comment]
Btw. the current spike is already consumable via JitPack:

Build Log: https://jitpack.io/com/github/testng-team/testng-junit5/master-SNAPSHOT/build.log
Coordinates:  https://jitpack.io/#testng-team/testng-junit5/master-SNAPSHOT

**Comment by krmahadevan** [comment]
@sormuras - Thanks. TestNG has been publishing SNAPSHOTS into sonatype via travis. We could perhaps have the `.travis` integration sorted out.

We basically need to add the following

1. the `deploy` folder ( you can refer [here](https://github.com/testng-team/reportng/tree/master/deploy) for a sample )
2. the `.travis.yml` file ( please refer [here](https://github.com/testng-team/reportng/blob/master/.travis.yml) for a sample)

Once that is done, I think @cbeust needs to embed the sonatype credentials into the travis project to get the builds to start publishing into Maven central snapshot repository.

**Comment by sormuras** [comment]
@krmahadevan Feel free to improve the deployment process right away. I'll concentrate on classes in `org.testng.junit5` for now.

**Comment by krmahadevan** [comment]
@juherr @cbeust - Can you please help with the credentials part in Travis to get started with publishing ? I have pushed in the travis file enhancements and also the deploy script.

**Comment by sormuras** [comment]
Using JDK 8 now. Done via https://github.com/testng-team/testng-junit5/issues/2

Now, the `pom.xml` needs some more love: https://travis-ci.com/testng-team/testng-junit5/jobs/142306674#L832

```
[ERROR] Failed to execute goal
  org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy)
  on project testng-junit5-engine:
Deployment failed:
  repository element was not specified in the POM inside distributionManagement element
  or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
```

**Comment by vlsi** [comment]
Just wondering, does https://github.com/junit-team/testng-engine implement the feature?

**Comment by juherr** [comment]
@vlsi Exactly
