### ISSUE TITLE
Priority tests are not executed

### ISSUE THREAD

**Issue by kralijir** [cbeust/testng#1853]
### TestNG Version
6.14.3

### Expected behavior
Priority/dependent tests are executed

### Actual behavior
Priority/dependent tests are not executed or the execution stuck. This is happening if I execute multiple test classes and one contains a test with priority and the another class contains a "dependsOnMethods" tests.
If I execute it one by one, there is no such issue. The same if I remove the "dependsOnMethods" test.

When I changed the version of TestNG to 6.11, the tests "numberOfDeparments2" are executed, but still the "numberOfDepartments1" are not executed.

When I execute large amount of test classes, it is also happening that the execution stuck once a dependent test should be executed in v6.14.3. There is no stuck in v16.11, but there is another issue (some dependent tests are not executed).
### Is the issue reproductible on runner?

- [ x] IntelliJ

### Test case sample
I am executing this TestNG 
```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="SPRE-API">
    <listeners>
        <listener class-name="common.core.listeners.TestListener" />
    </listeners>

    <test name="Priority tests">
        <classes>
            <class name="testsuites.spretests.Test1" />
            <class name="testsuites.spretests.Test2" />
        </classes>
    </test>
</suite>
```

Here are the tests:
```java
public class Test1 {

    @Test(groups = {"GET", "POST", "PUT", "DELETE", "SPRE"})
    public void verifyDepartments() throws IOException{
        System.out.println("This is no priority tests from test1");
    }


    @Test(groups = { "GET", "SPRE"}, priority = 3)
    public void allDepartments(){
        System.out.println("This is priority=3 tests from test1");
    }

    @DataProvider(name = "validParameters")
    public static Object[][] validParametersData() {
        return new Object[][] { {"1", 1, 0}, {"2",  2, 1}, {"3", 2 , 0},
                {"4",  2+1 , 0}, {"5",  2 , 2-1}
                ,{"6",  2+1, 2+1},{"7",  1, 2-1}, {"8", 1, 9999}};
    }

    @Test(dependsOnMethods = "allDepartments", dataProvider = "validParameters")
    public void numberOfDepartments(String step, Integer limit, Integer offset) throws IOException{
        System.out.println("This is dependOnMethods tests from test1");
    }

}
```

and the second test class:
```java
public class Test2 {

    @Test(groups = {"GET", "POST", "PUT", "DELETE", "SPRE"})
    public void verifyDepartments2() throws IOException{
        System.out.println("This is no priority tests from test2");
    }

    @Test(groups = { "GET", "SPRE"})
    public void allDepartments2(){
        System.out.println("This is no priority tests from test2");
    }

    @DataProvider(name = "validParameters")
    public static Object[][] validParametersData() {
        return new Object[][] { {"1", 1, 0}, {"2",  2, 1}, {"3", 2 , 0}};
    }

    @Test(dependsOnMethods = "allDepartments2", dataProvider = "validParameters")
    public void numberOfDepartments2(String step, Integer limit, Integer offset) throws IOException{
        System.out.println("This is dependsOnMethod");
    }

}
```

**Comment by krmahadevan** [comment]
Please do not combine priority and `dependsOnMethods`. You are asking for trouble if you do that, because both these are basically mechanisms of establishing a certain order.

From the example here's what you have

```
Test1.verifyDepartments() [p0]
Test1.allDepartments()[p3]
Test1.numberOfDepartments()[p0, dependsOn="allDepartments"]

Test2.verifyDepartments2() [p0]
Test2.allDepartments2()[p0]
Test2.numberOfDepartments2()[p0, dependsOn="allDepartments2"]
```

Now when TestNG would commence execution with `Test1` it finds that you have both dependsOnMethods and priority combined (since at least one method has a non zero priority, it is assumed that priority now exists in your execution).

`dependsOnMethods` and `dependsOnGroups` are basically hard dependencies (which means if the upstream method failed, then the downstream method doesn't get executed).
`priority` is a soft dependency (which means there's no downstream skip if the upstream method failed)

By behavior TestNG gives more preference to hard dependencies.

So in your case, first TestNG will try to satisfy `dependsOnMethods`.

So `Test1.numberOfDepartments()[p0, dependsOn="allDepartments"]` is not executed immediately. But it has a priority of zero, which means it should be executed first (if there was no dependency)

TestNG now proceeds to figure out independent methods (methods that have no dependency). So the below two qualify

```
Test1.verifyDepartments() [p0]
Test1.allDepartments()[p3]
```

So now it tries to execute all `p0` methods. It succeeds in executing `verifyDepartments()` but cannot still execute `Test1.numberOfDepartments()` even though its a p0 method since it has a hard dependency on `Test1.allDepartments()[p3]`. But unfortunately `allDepartments()` is a `p3` method and can only be executed after all the `p0,p1,p2` methods have run to completion.

So essentially you have created a deadlock.

Please either use priority (or) `dependsXXX` but not both.
