### ISSUE TITLE
Maven Email Report Customization: Test method Parameters are not available in testng Listener email report.

### ISSUE THREAD

**Issue by rajatjain05** [cbeust/testng#1922]
Currently my test method is getting data from Data Provider (Data like Username and Password), after the execution I am getting an email by Listener that have details of Failed/Passed test method name. I have 1 test method that runs for 40 username and password. I want my email should contain Username for which test method is Failed/Passed instead of Test method name alone. What thing I need to implement in Listener implementation class?

Currently getting email in this form:
![image](https://user-images.githubusercontent.com/43569846/46006940-5700ba80-c0d6-11e8-9151-81d4c5812ac8.png)

But the requirement is to have different Usernames in place of "mainTest_VM_API".

**Comment by juherr** [comment]
What if you test implements `ITest`?

**Comment by krmahadevan** [comment]
@rajatjain05 - Am not quite sure what version of TestNG you are using. The parameter information is available in the TestNG e-mailable report. Please see below screenshot from the latest released TestNG version viz., **7.0.0-beta1**

Also from the screenshot, it doesn't look like a TestNG report to me. AFAIK, none of the TestNG default reports have that look and feel.

Closing this issue. If this is still a problem, please feel free to add more contextual information in the comments so that we can investigate this more. 

![screen shot 2018-11-08 at 8 45 29 pm](https://user-images.githubusercontent.com/909773/48207836-870ad100-e397-11e8-8a52-c2d3f0dcba25.png)


Here's the sample that I used for this test 

```java
import java.io.File;
import org.testng.Reporter;
import org.testng.TestNG;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestclassSample {
  @Test(dataProvider = "dp")
  public void testMethod(String uname, String password) {
    String location = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
    String version = new File(location).getParentFile().getName();
    Reporter.log("TestNG version = " + version, true);
    Reporter.log("Username = " + uname + ", Password = " + password, true);
  }

  @DataProvider(name = "dp")
  public Object[][] getData() {
    return new Object[][] {
      {"admin", "password"},
      {"user", "userpassword"}
    };
  }
}

```
