### ISSUE TITLE
Assert class is missing in beta4

### ISSUE THREAD

**Issue by baflQA** [cbeust/testng#2051]
### TestNG Version
7.0.0-beta4
### Expected behavior
Assert.class is present in org.testng package

### Actual behavior
Assert.class is gone in beta4

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
Hi/ I've just updated to beta4, and I've noticed that Assert.class is missing and my project won't compile. It's not marked as deprecated in beta3, so I guess that something went wrong during the release.

**Comment by cbeust** [comment]
Yes, something went wrong wiht beta4. Ignore it, I'll deploy a beta5 soon.

**Comment by frew** [comment]
@cbeust As a heads up, it appears that this leaves users in a pretty unfortunate situation where anything processing one of the testng generated XML files (e.g. testng-FAILED.xml) and using Xerces to parse it hits the http->https redirect problem for the DTD and since beta4 was the only version with the new URL, there's no fix. Possible to either cut a new release or revert the http->https redirect change until new release is ready?

**Comment by cbeust** [comment]
beta5 is available on JCenter.

**Comment by frew** [comment]
Thanks! Tried beta5 and seems to have resolved the issues.

**Comment by escay** [comment]
For google searches:

also classes like 
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

have been missing in beta4.
