### ISSUE TITLE
Release 7.1.0 rc

### ISSUE THREAD

**Issue by Drimix20** [cbeust/testng#2176]
Hello guys,
can you please release 7.1.0 release candidate to be able to tryout new bug fixes? Or what is recommended procedure to validate bug fixes on my dev environment?

**Edit:** Attached @cbeust 

Thank you. 

Drimix20

### TestNG Version
7.0.0

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by juherr** [comment]
@krmahadevan Do you think it is possible to publish an alpha or beta version?

**Comment by krmahadevan** [comment]
@juherr - I think only @cbeust can do the releases right? I dont have any reservations with us doing an `alpha` or a `beta` release

**Comment by cbeust** [comment]
We still automatically upload snapshots from Jenkins, don't we?

**Comment by krmahadevan** [comment]
@cbeust - I dont think we are uploading any snapshots from Travis to Maven snapshots repo [ See [here](https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/) ]

**Comment by Drimix20** [comment]
Any progress on this?

**Comment by gauravdeshmukh612** [comment]
Any plan for new release ?
ping: @cbeust, @krmahadevan, @juherr

**Comment by krmahadevan** [comment]
@cbeust @juherr what do you say ? I think we can go ahead with a minor release

**Comment by gauravdeshmukh612** [comment]
Yes Please @cbeust @juherr

**Comment by juherr** [comment]
No problem for me.

**Comment by cbeust** [comment]
Alright, I'll get the release ready. Take a look at the CHANGELOG and feel
free to edit it so the new features/fixes are apparent.

-- 
Cédric

**Comment by gauravdeshmukh612** [comment]
Can you please tell release date ?

**Comment by baflQA** [comment]
Hi guys! I just tried the 7.1.0 from the spring repo, and I'm getting 

```
java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener2
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1204)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1215)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1259)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1294)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1379)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:898)
	at org.testng.TestNG.initializeEverything(TestNG.java:988)
	at org.testng.TestNG.run(TestNG.java:999)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.ClassNotFoundException: org.testng.IInvokedMethodListener2
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 22 more
```
when trying to run my tests from IntelliJ.

**Comment by hkrizek** [comment]
@baflQA ,
I have the similar issue with JIdea 2019.3:
`Receiver class com.theoryinpractice.testng.configuration.TestNGRunnableState does not define or inherit an implementation of the resolved method 'abstract void configureRTClasspath(com.intellij.execution.configurations.JavaParameters, com.intellij.openapi.module.Module)' of abstract class com.intellij.execution.JavaTestFrameworkRunnableState.`

When running by maven I had the same issue, but with maven.surefire-plugin and I solved it by using the newest 3.0.0-M4. What is your version of JIdea ? IInvokedMethodListener2 was deprecated in the latest testng 6. This could be an issue of testng plugin in IntelliJ.

**Comment by juherr** [comment]
Release done: https://search.maven.org/artifact/org.testng/testng/7.1.0/jar

**Comment by ERankur91** [comment]
@juherr 
Still getting same issue:
` <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.1.0</version>
        </dependency>`
`[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] org/testng/IInvokedMethodListener2
[ERROR] java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener2
[ERROR] 	at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[ERROR] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[ERROR] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	at java.lang.Class.forName0(Native Method)
[ERROR] 	at java.lang.Class.forName(Class.java:348)
[ERROR] 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
[ERROR] 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
[ERROR] 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[ERROR] 	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
[ERROR] 	at org.testng.TestNG.initializeConfiguration(TestNG.java:898)
[ERROR] 	at org.testng.TestNG.initializeEverything(TestNG.java:988)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:999)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.testng.IInvokedMethodListener2
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	... 28 more
[ERROR] 
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org/testng/IInvokedMethodListener2
[ERROR] java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener2
[ERROR] 	at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[ERROR] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[ERROR] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	at java.lang.Class.forName0(Native Method)
[ERROR] 	at java.lang.Class.forName(Class.java:348)
[ERROR] 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
[ERROR] 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
[ERROR] 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[ERROR] 	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
[ERROR] 	at org.testng.TestNG.initializeConfiguration(TestNG.java:898)
[ERROR] 	at org.testng.TestNG.initializeEverything(TestNG.java:988)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:999)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.testng.IInvokedMethodListener2
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	... 28 more
[ERROR] 
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
`

**Comment by juherr** [comment]
@ERankur91 Please try `7.3.0` which is the latest supported version.

**Comment by ERankur91** [comment]
> @ERankur91 Please try `7.3.0` which is the latest supported version.

@juherr And specific version of maven surefire plugin suggested?

**Comment by juherr** [comment]
> And specific version of maven surefire plugin suggested?

@ERankur91 Try the latest release.
