### ISSUE TITLE
@BeforeSuite cannot autowire MockMvc

### ISSUE THREAD

**Issue by cenyu00** [cbeust/testng#2191]
### TestNG Version
> Note: only the latest version is supported
7.0.0

### Expected behavior
autowire MockMvc in springboot project

### Actual behavior
cannot autowire MockMvc in springboot project

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

in springboot 2.1.7 project.
I test HTTP RESTful in controller layer， use MockMvc mock HTTP Request。
in `@Test` annotation method ，this MockMvc can be autowire，but，in `@BeforeSuite` annotation method, the  MockMvc is null.

this class:

```java
@SpringBootTest(classes = DmsServerApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@AutoConfigureMockMvc
public class MetaTest extends AbstractTestNGSpringContextTests {

    @Autowired
    private MockMvc mockMvc;


    @BeforeSuite
    public void setUp() throws Exception {
        // mock request http

    }

}
```

what can i do ?

**Comment by krmahadevan** [comment]
@cenyu00 - `AbstractTestNGSpringContextTests` is not owned by TestNG project.  You would need to file an issue in the spring boot project and not here.

**Comment by FabianSawatzki1234** [comment]
We are experiencing the same issue. The order in which the Before- and After-Methods are called has changed. Actually they are called before the spring context is loaded. This worked fine before 7.0.0. There must be some changes in your code that lead to this issue. So I am wondering why this issue was closed?

**Comment by krmahadevan** [comment]
@FabianSawatzki1234 - If the spring testng integration depends on the order in which TestNG is invoking this, and if TestNG has fixed/changed the order in which this is being invoked, shouldn't the spring testng project basically fix things at their end by adjusting their code to work fine with the latest TestNG released version ?

TestNG has no control over the spring testng project and thus this issue was closed because its not in scope of the TestNG project.
