### ISSUE TITLE
NullPointerException with instance @BeforeClass

### ISSUE THREAD

**Issue by vladimirk** [cbeust/testng#2294]
I believe this issue exists because of the core design of TestNG. The question is why @BeforeClass and @BeforeMethod arent static methods? This will eliminate the broken semantics of the regular java class, will eliminate the need for instantiating the test instances elsewhere which causes a bunch of special effects if they are doing something with side effects in constructors (like creating files). Is moving to static methods for class and suite annotations something that could be considered?

### TestNG Version
7.1.0

### Expected behavior

Run as a suite test should pass successfully.

### Actual behavior

One of the tests will fail with NullPointerException.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample

```java
public class AbstractTest {
  String field;
  @BeforeSuite
  public void assignField() {
    this.field = "test";
  }
}

public class TestA extends AbstractTest {
  @Test
  public void test() {
    this.field.size();
  }
}
public class TestB extends AbstractTest {
  @Test
  public void test() {
    this.field.size();
  }
}
```

**Comment by krmahadevan** [comment]
The problem lies in your test code.

You are initialising the field `field` via a `@BeforeSuite` annotated method which gets executed **ONLY ONCE** per `<suite>`

So either `TestB` or `TestA` is bound to encounter a NullPointerException because for the second class, the `assignField()` method never would get executed.

You should be using a `@BeforeClass` annotation

Closing this issue with the resolution as **Question answered**

**Comment by vladimirk** [comment]
I know the reason. The question is why it behaves that way. From the pure java standpoint, this classes are correct. It is intuitively expected to work fine. 

Since @BeforeSuite is expected to be executed once for a suite, it is reasonable for this method to be static. This way there will be no possibility to write such an erroneous code.

@krmahadevan

**Comment by krmahadevan** [comment]
@vladimirk 

> From the pure java standpoint, these classes are correct. It is intuitively expected to work fine.

You are trying to apply java constructs to a test framework that has its own rules and regulations. Even the other test framework such as JUnit has its own rules (for e.g., for every test method the test class is instantiated again, at least to the best of my knowledge that's how it works. )

> So, in general, the question is whether it will be better if the test classes behave as regular java classes.

I dont know what is the thought process behind this expectations. In either case, I would let @cbeust pitch in and explain better since he created TestNG and should be better poised to answer this question.

> Every test class is expected to be instantiated only ones. Because now the number of instances of the class is unpredictable for the test writer.

Where is this expectation coming from? Why should tests be worried about the number of instances of a class that is getting created ?

**I am re-opening this question just to ensure that there's a proper answer to this query and not because this is going to be fixed from a code perspective**

**Comment by juherr** [comment]
The choice of instance methods for configuration instead of static methods is one of the initial reason of why TestNG exists. See the @cbeust 's blog entry: https://beust.com/weblog/2004/08/25/testsetup-and-evil-static-methods/

I don't know if the support of static methods could be expected or not. I suppose we should, at least, warn about the "bad" practice when it is used.

**Comment by vladimirk** [comment]
@krmahadevan 

I'm just expressing the opinion of whether it is good if any framework changes the basic language rules. Especially if it's not particularly necessary. I'm not against instantiating classes multiple times per se, I'm just pointing out that unpredictable instantiating is something problematic. 

Let me show you the log and explanatory example that brought this discussion:
```
[17:28:34] :     [Step 2/6] [INFO] -------------------------------------------------------
[17:28:34] :     [Step 2/6] [INFO]  T E S T S
[17:28:34] :     [Step 2/6] [INFO] -------------------------------------------------------
[17:28:34] :     [Step 2/6] [INFO] Running TestSuite
[17:28:35] :     [Step 2/6] initializing test directory /tmp/test/temp_vieworks-account_2.5.3-281_1586366915219
[17:28:35] :     [Step 2/6] 17:28:35.253 [main] DEBUG oap.storage.mongo.MongoFixture - binding MONGO_DATABASE to db_vieworksaccount_2_5_3281_1586366915250 by oap.storage.mongo.MongoFixture@46fa7c39
[17:28:35] :     [Step 2/6] 17:28:35.280 [main] DEBUG oap.storage.mongo.MongoFixture - binding MONGO_DATABASE to db_vieworksaccount_2_5_3281_1586366915280 by oap.storage.mongo.MongoFixture@61386958
[17:28:35] :     [Step 2/6] 17:28:35.344 [main] DEBUG oap.storage.mongo.MongoFixture - binding MONGO_DATABASE to db_vieworksaccount_2_5_3281_1586366915344 by oap.storage.mongo.MongoFixture@4fb3ee4e
[17:28:35] :     [Step 2/6] 17:28:35.364 [main] DEBUG oap.storage.mongo.MongoFixture - binding MONGO_DATABASE to db_vieworksaccount_2_5_3281_1586366915364 by oap.storage.mongo.MongoFixture@2c35e847
```
4 times the test class was instantiated by the framework before the test even started. Parallel execution is prohibited in configuration, this classes were instantiated for framework purposes.
 
The problem lies here (pseudo java code):
```java
public class SettingSystemProperty {
  static int counter = 0;
  public SettingSystemProperty() {
      System.setProperty("prop", counter++);
  }
}

public class Test {
    private SettingSystemProperty ssp;  
    private int fromConstructor;
    public Test() {
      this.ssp = new SettingSystemProperty(); 
      this.fromConstructor = System.getProperty("prop");
    }
    @BeforeClass
    public void before() {
            //you wish. Sometimes.
            assertEquals(this.fromConstructor, System.getProperty("prop"));
    }
    @AfterClass
    public void after() {
            //forget about it
            assertEquals(this.fromConstructor, System.getProperty("prop"));
    }
}  
```
See the problem?

And the worst part that it's environment-dependent. Fine within Idea. It might be ok in the local maven run. Failed at Teamcity. 

I'm not suggesting that static methods are the only way to go. I'm fine with any solution that makes test instantiation controlled predictable process. The alternative might be making @BeforeSuite methods not to be placed into @Test enabled classes. 

Junit5 addresses this with static methods only annotation @BeforeAll. 
I agree with @juherr note about statics. But with such unpredictable instantiations, I'm forced to put lots of things into statics to guarantee the execution order.  The problem with the statics in general terms is the race conditions on the common state. But with the current implementation, the race conditions and the common state is exactly what is causing the problem, because test case class is not self-contained. It doesn't event have guarantees of the regular java class.

What do you think?

The ideal semantics would be 
@Before/AfterSuite methods executed only once on an instance that is instantiated only once and cannot contains @BeforeClass/Method annotations.
@Before/AfterClass/Method invoked only on the single instance of the class. 
Test class is guaranteed by the framework to be instantiated only once (This behavior could be controlled by some annotation like @TestConfiguration(allowParallel = true | false) on the class itself.

**Comment by krmahadevan** [comment]
@vladimirk - Maybe I am missing something obvious here, but what is the issue with the example that you shared ? I may be missing something obvious here.

Are you hinting that if a user ends up embedding some test specific computational logic within the test classes constructor thinking that the constructor is going to get called only once, then he/she maybe misled because the test framework is creating multiple instances of that test class ?

If that's the case, I guess that it would be a wrong way to use the test framework because like I said one would need to familiarise oneself with the test framework's rules and semantics no ?

With respect to the semantics that you are proposing, I would let @cbeust take a call on that because this will significantly deviate from the basic behaviour of TestNG

**Comment by vladimirk** [comment]
@krmahadevan About the example, the issue will be that fromConstructor value and actual system property would be unpredictably different. 

The problem I see is that it's not obvious semantics of the framework restricting users not helping them, and the reason for this is a framework internal design. As it is now it restricts the programming language with no good reason to do so - there are no gains in that design, specifically, it instantiates the classes because @BeforeSuite are instance methods, and they are sitting by the ones next to the test. If the method were static or required to be implemented in a separate class, there will be no reason left to instantiate test classes rather than for execution purposes local to them, and the problem will go away.  

What I'm proposing is (i believe) thinking about the next version design which has no such restrictions. The core thing for it is the user's control over the test instantiation since he can possibly invoke something during instantiation that has side effects. In the example case, the user doesn't even use any kind of features that require more than one instantiation of the test class at a time (no parallelism, no @BeforeSuite), nevertheless, the framework did it anyway, without the possibility to restrict such behavior.

**Comment by juherr** [comment]
@vladimirk You are not supposed to do things in the constructor of test classes like you are not doing it with any other framework (Hibernate, Spring, ...).

Instead, TestNG offers some ways to be notified: callback with configuration methods or listeners.
If you want to share object instances, you can use the Guice support too.

Sometimes, it could be complicated to manage tests when your suite is complicated. But it is not the case most of the time.

On my side, I don't see any reason to change the design, just some pro and cons users have to learn before using the tool.

**Comment by vladimirk** [comment]
@juherr There is nothing illegal going on in constructor, this kind of logic works anywhere else. 

Maybe you can help me understand the pros of that design. I understand what the framework is doing. I definitely see the cons, some of them are shown here. I'm struggling to see the pros. 

Given unit testing frameworks evolution I understand how it was born. Don't see why it can't be improved thou, given the problem listed above with the current design.

**Comment by juherr** [comment]
@vladimirk Sure, there is nothing illegal but you can fight against the framework or deal with it.
TestNG, as a test container, doesn't specify how and when test classes are created.
Maybe there is a bug and there are too many creations; I didn't check.

Of course, it can be improved but it will a too much effort we are not able to provide (I think the change could be huge). Maybe you'd like to have a look at it?

About your initial question: `@BeforeSuite` is called once by suite and not once by instance in the suite. You can choose to set `field ` static or not.
TestNG could support static methods for some callbacks (*Suite, *Group, *Class) but I'm not sure it is a so good idea.

**Comment by cedricbeust-okta** [comment]
> I'm just expressing the opinion of whether it is good if any framework changes the basic language rules. 

This happens all the time in any library that acts as a container and/or provides lifecycle functions. For example, JUnit reinstantiates your entire class in-between method calls. Not exactly intuitive nor something that the language does, but nobody really minds as long as these rules are clearly documented.

I think the argument that `@BeforeSuite` should be static has some merit, but not `@BeforeClass`, since TestNG allows you to put code in `@BeforeClass` that will initialize instances differently (and TestNG maintains the same instance through method calls, unlike JUnit).

Note also that nothing prevents you from making `@BeforeSuite` static (I think?), so you can already do this today, although TestNG itself won't expect this nor leverage it.

**Comment by krmahadevan** [comment]
@juherr @cbeust - So what is the consensus on this? Does this need to be fixed (If yes, what is the nature of the fix?) ? If not, can we close this off ?

**Comment by juherr** [comment]
Maybe TestNG could warn users when "bad practices" are detected like static configuration methods when not expected. It could help them to understand why it is not working as expected.

**Comment by krmahadevan** [comment]
@juherr - So the PR for this issue should basically detect static configurations and start logging warning messages against them on the console so that the user is warned. That should suffice right ? I will go ahead and raise a PR for that shortly.

**Comment by juherr** [comment]
Yes, I think it will be enough 👍

**Comment by krmahadevan** [comment]
warning added as part of https://github.com/cbeust/testng/pull/2369 so closing this issue.
