### ISSUE TITLE
Request for formal release

### ISSUE THREAD

**Issue by bj-9527** [cbeust/testng#2421]
### TestNG Version
> 7.3.0

### Expected behavior
We have uplifted to the latest version of TestNG, but there are some issues blocked us, like #[2403](https://github.com/cbeust/testng/issues/2403) and #[2357](https://github.com/cbeust/testng/issues/2357)

### Actual behavior
Do we have a plan to do a formal release, a small version uplift like 7.3.1 is OK to us.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by slawekjaranowski** [comment]
any news ...

**Comment by krmahadevan** [comment]
@bj-9527 @slawekjaranowski - The release is in the plan but before it happens we would like to do two things:

1. Close off all the in-flight PRs that are being reviewed.
2. Close out a few more issues (Right now we have just 21 issue fixes).

**Comment by bj-9527** [comment]
OK, sure. Maybe you can assign me several issues which you think should be solved before release, I would like to fix them first.

**Comment by krmahadevan** [comment]
@bj-9527 - To be honest, I haven't had the time to triage out the issues and figure out which of them can be included for the upcoming release. So I dont have a list of issues readily available at my hands which I can pass on. So please feel free to take a jab at as many issues as you can and help fix. The more the merrier. I was hoping that we could perhaps target a release maybe end of this year (Christmas release)  or first week of Jan 2021 (new year release). And I was hoping that we could atleast get to fixing some 40 odd issues.

@juherr @cbeust - All said and done, I think we should perhaps start looking at defining our release timelines (quarterly or monthly) or something on those lines so that our users know when is the next release coming. Your thoughts on this ?

**Comment by slawekjaranowski** [comment]
Maybe `Milestone` feature of GitHub will be the best solution for planning and transparency next releases. 

Everyone who is interested or want to help for next release can see what should be done.

**Comment by krmahadevan** [comment]
@slawekjaranowski - Sure. But like I said, we would first need to define the release frequency basis (Is it based on the chunk of features/bugs or is it based on duration). That is where I was hoping to get some insights from Cedric and Julien.

On the logistics side, TestNG does not have a very big dev team. It has been pretty much mostly just me and @juherr . So all of those planning stuff is kind of hard to make it happen for want of time.

**Comment by juherr** [comment]
I don't see the interest in having a periodic release because the amount of changes depends on the free time of too few persons.
As an alternative, we could have a periodic beta release and make the final release only when we feel it right.
Users will be able to choose between the latest changes quickly but riskier, or using a more stabilized version.

WDYT?

**Comment by slawekjaranowski** [comment]
What do you think about release automatically new version from master branch after each commit or periodically eg. once a week or else period.

If you really need you can create separate branch for stable release .... but this make more work for you.

Another idea - from time to time you can release next major version.
Automatically release will only change build - so user will know which version use, eg 7.3.0 - last stable .... 7.3.N last release from master.

Last time I refreshed mockito-testng project and I have release after each commit. 
Similar release process is in mockito project.

**Comment by juherr** [comment]
Instead of a release for each commit, I'd prefer to use Jitpack and we already have an issue about this subject:  https://github.com/cbeust/testng/issues/2391

**Comment by stachenov** [comment]
Any updates? #2403 is going to become a bigger problem because JCenter is apparently going down soon, and TestNG 7.1.1, which is the best version that doesn't have this bug, is not present in Maven Central, only in JCenter. So a new release in Maven Central with #2403 fixed would be nice.

**Comment by krmahadevan** [comment]
@stachenov - `7.4.0` should most probably be released this weekend.

**Comment by krmahadevan** [comment]
TestNG 7.4.0 is now released into maven central.
