### ISSUE TITLE
Duplicate Version template file

### ISSUE THREAD

**Issue by alexander-poulikakos** [cbeust/testng#2450]
### TestNG Version
latest on master branch. Hash: a105fbe1e507bed289b4778968d6669c3e4aaae1

### Expected behavior
TestNG should build

### Actual behavior
This file is not compiling in my IDE (Eclipse):
https://github.com/cbeust/testng/blob/master/src/main/resources/Version.java
With the error message:
```
/testng/src/main/resources/Version.java
The declared package "org.testng.internal" does not match the expected package ""
```
Which seems like a good error message since the file is declared in default package, but file expect it to be in "org.testng.internal" package.

Is this expected? Or am I missing something?

![image](https://user-images.githubusercontent.com/16044466/104197176-fc193b80-5424-11eb-81ed-712adb03a004.png)

**Comment by juherr** [comment]
`src/main/resources/Version.java` is a template file in a resources folder.
It is duplicate with the VersionTemplateJava file and we should remove one of them.

As I remember, eclipse doesn't make any difference between sources and resources folders. That's why it is trying to compile it.
You should be able to build TestNG with Maven without any problem.

I keep the issue open in order to remember to remove the duplicate file.

**Comment by alexander-poulikakos** [comment]
yeah, it is probably the `.java` file ending that confuses Eclipse.  Better keep the `VersionTemplateJava` one.
