### ISSUE TITLE
TestNG 7.3.0/7.0.0 create a lot of WAIT_STATUS threads

### ISSUE THREAD

**Issue by xuanzhaopeng** [cbeust/testng#2514]
### TestNG Version
7.4.0 looks "fine",  but it happened at 7.3.0 and 7.0.0 

### Actual behavior
When I trigger 40 threads for "method" level parallel tests through Maven surefire plugin (3.0.0-M5, latest version, default settings for fork), "it" creates a lot of(created 300 threads in wait status in 10 mins in my local laptop, it will be even worse in CI machine, it will be 1000+ threads in wait status ) Those threads doesn't have name, such as below

<img width="1037" alt="Screenshot 2021-04-06 at 20 32 14" src="https://user-images.githubusercontent.com/5563244/113762234-aa790800-9718-11eb-8311-39bf45f00218.png">
 
I don't know what's the expected behaviour... 

Here is some result in my laptop, (my laptop is more slower than the CI/CD, in CI/CD, we will see this change even more faster)

7.0.0:
<img width="1442" alt="Screenshot 2021-04-06 at 21 24 51" src="https://user-images.githubusercontent.com/5563244/113767107-8caea180-971e-11eb-9b30-ec7053b322e5.png">

7.3.0:
<img width="1388" alt="Screenshot 2021-04-06 at 21 25 21" src="https://user-images.githubusercontent.com/5563244/113767157-9cc68100-971e-11eb-9016-88d21ec29a4e.png">

for 7.4.0
<img width="674" alt="Screenshot 2021-04-06 at 21 46 44" src="https://user-images.githubusercontent.com/5563244/113769741-9c7bb500-9721-11eb-901b-e6efb7ba24c4.png">

Even in 7.4.0, we also have these sleep threads. But seems these sleep threads won't increased endlessly. I don't understand why, maybe you can share some ideas what's this logic behind these sleep threads? and what's the usage for?

<img width="1305" alt="Screenshot 2021-04-06 at 21 29 46" src="https://user-images.githubusercontent.com/5563244/113767712-4f96df00-971f-11eb-8c95-afda50b0943e.png">

### Expected behavior
I expect we should NOT create a lot of threads in wait_status.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> not really related to test case

**Could u pls let me know which changes in 7.4.0 fix this issue? and what's the purpose of creating these sleep threads?**

It would super appreciated that we could understand how it works and how it be fixed

**Comment by krmahadevan** [comment]
@xuanzhaopeng - Couple of things:

1. TestNG resorts to explicit waits via `Thread.sleep()` when: 
    1.  A `@Test` method involves a `timeout` (or) an `invocation`defined.
    2. The `parallel` attribute defined is anything except `tests`
    3. If the current thread was something that was already spun off by TestNG, then we tend to re-use that thread. This usually happens when we have say a suite of suites and suites are being run in parallel.  I have to think a bit more to find out under what other circumstances this item will be true. @juherr do you know what are the other situations wherein [this](https://github.com/cbeust/testng/blob/4170ef68fb8203265cba4f6bfdbfb9c4a0b63f05/src/main/java/org/testng/internal/MethodInvocationHelper.java#L276-L281) condition becomes true ?
   When this happens we end up sleeping till the Thread's defined timeout. 
2. Since the cause of the problem statement can be ascertained only with a sample, not sure what was causing the problem  and what fix in `7.4.0` fixed this issue. So it would be difficult for me to comment on the exact changeset that perhaps has fixed this problem as a side effect. We did do some changes in terms of the performance improvement and memory foot print reduction. For e.g., this one issue https://github.com/cbeust/testng/issues/2096 had atleast 4 pull requests to bring down the memory foot print. I dont recollect us doing anything in this area that could have improved this experience any better.

So here's the ask from you.

1. If this problem is still seen with `7.4.0`, please help share a sample that we can use to reproduce this issue. I ask this because as you also might agree, these sort of issues are hard to reproduce and it would be great if we have a sample to play around with.

**Comment by xuanzhaopeng** [comment]
Hey @krmahadevan ,  I tested in past hour in our production test environment after I move from 7.3.0 to 7.4.0. 

It works properly now(at least it won't a blocker for us anymore)

I think we can close this issue , since I'm also wondering the issue has been silently fixed by https://github.com/cbeust/testng/issues/2096 

Thanks
Robin
