### ISSUE TITLE
TestNG 7.4.0 throws an exception "The version of TestNG used does not support setting config failure policy to 'continue'" 

### ISSUE THREAD

**Issue by AsDmitrij** [cbeust/testng#2533]
### TestNG Version 7.4.0
> Note: only the latest version is supported

### Expected behavior
Configfailurepolicy is configured as "continue" and tests should pass when run

### Actual behavior
Error appears: The version of TestNG used does not support setting config failure policy to 'continue'.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
> https://github.com/AsDmitrij/Continue.git

**Comment by krmahadevan** [comment]
@AsDmitrij - This is a compatibility problem that Gradle is having with TestNG. I think you need to take this up with Gradle than with TestNG because Gradle is still referring to a method that was removed. Closing this issue since there's nothing to be done from TestNG side.

Here's the stacktrace when you run 

```
./gradlew clean test --stacktrace
```

```
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NoSuchMethodException: org.testng.TestNG.setConfigFailurePolicy(java.lang.String)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestFramework.verifyMethodExists(TestNGTestFramework.java:108)
        ... 104 more
```

**Comment by siordache** [comment]
@krmahadevan I see that you already [opened a Gradle issue](https://github.com/gradle/gradle/issues/10507) related to this problem back in 2019. However, the issue has been ignored by the Gradle team and closed by the stale bot.

I assume that the Gradle team didn't fix it because Gradle [uses reflection](https://github.com/gradle/gradle/blob/b91bcc5f464cec06229df4420c9ae2ac79865fe9/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java#L112) to call the `setConfigFailurePolicy` method. Having to choose the right method to call (depending on the TestNG version) and calling via reflection a method with a FailurePolicy parameter would make the code ugly. While this is no excuse for Gradle to let the bug unfixed, it would be nice if in this case TestNG would get rid of the problem by adding to TestNG.java a `setConfigFailurePolicy` convenience  method with the same signature as in older releases:

```
  public void setConfigFailurePolicy(String failurePolicy) {
    m_configFailurePolicy = XmlSuite.FailurePolicy.getValidPolicy(failurePolicy);
  }
```

What do you think?

**Comment by juherr** [comment]
@siordache No need to add a method for that. For integration projects like gradle, we already manage api changes via testng-team/testng-remote

**Comment by siordache** [comment]
Thanks, @juherr. I'm not familiar with testng-remote. Can you please explain how should one use it in order to get rid of the NoSuchMethodException when executing `./gradlew clean test`?

**Comment by juherr** [comment]
@siordache `testng-remote` is our project that deals with the API changes. `testng-eclipse` uses it. It could be an option if we add `setConfigFailurePolicy` support and gradle integrates it.
I've no idea why gradle doesn't upgrade its usage of TestNG api.

**Comment by siordache** [comment]
Ok. thanks! I [passed this information](https://github.com/gradle/gradle/issues/10507#issuecomment-963127091) to the Gradle team.

**Comment by rookieInTraining** [comment]
@siordache - As a workaround, we can use the `IAlterSuiteListener` and override the alter method to set the `configFailureAPolicy` to continue `suite.setConfigFailurePolicy(XmlSuite.FailurePolicy.CONTINUE)` . I faced the same issue as you've mentioned and had to resort to this in order to continue.
