### ISSUE TITLE
Unable to install TestNG. 

### ISSUE THREAD

**Issue by Prateeksha42** [cbeust/testng#2534]
The link provided in the official TestNG website **[](https://dl.bintray.com/testng-team/testng-eclipse-release/)** is Forbidden

Even in the Eclipse Marketplace, Its causing same issue

![Screenshot (71)](https://user-images.githubusercontent.com/53993726/116834921-d97e7e80-abdd-11eb-8510-05e774d4a75c.png)

**Comment by krmahadevan** [comment]
Please refer to the instructions in https://github.com/cbeust/testng-eclipse#install-snapshot

If its still a problem, please open an issue with https://github.com/cbeust/testng-eclipse project.

**Comment by missedone** [comment]
hi guys, because bintray.com sunset on May 1, so we have moved the update-site to github, 
* new update site url: https://testng.org/testng-eclipse-update-site
* the source is at https://github.com/testng-team/testng-eclipse-update-site

we will update the url on eclipse marketplace soon.

see more details: https://github.com/cbeust/testng-eclipse/issues/511#issuecomment-827179825
