### ISSUE TITLE
Guice 5.0 drops no-aop variant, so TestNG should probably upgrade and avoid no-aop dependency

### ISSUE THREAD

**Issue by vlsi** [cbeust/testng#2576]
See https://github.com/google/guice/wiki/Guice501#changes-since-guice-423

**Comment by vlsi** [comment]
Note: one of the changes in Guice 5 is `Removed cglib as a core dependency` which is nice since `cglib` has issues with compatibility with modern Java versions (and `cglib` is not that needed for modern Java as it was in Java 1.4 days :) ).

**Comment by juherr** [comment]
@vlsi Be careful: the more you add issues, the more you take the risk to have merge conflicts in your own PR :p

**Comment by krmahadevan** [comment]
@juherr - A bit confused here. Please help clarify.

I was under the assumption that the no-op basically provides the apis as dummy interfaces just to keep the compiler happy and help with building the testng codebase.

The real user is still required to provide with an actual Guice dependency in their classpath for them to be able to leverage Guice backed Dependency Injection.

In that case 

1. How does it matter as to what version of Guice the TestNG has as a dependency and how is depending on aop going to be a concern.
2. The latest dependency changes that were introduced as part of PR https://github.com/cbeust/testng/pull/2577 seems to be bringing in the actual dependency. So what would happen when a user consumes this latest version of TestNG and tries to use it with their existing project which uses an earlier version of Guice ? Wouldnt it cause classpath collisions ?

@bj-9527 - FYI. Once we have clarity on the answers to these questions, we can go ahead and get your changes merged.

**Comment by juherr** [comment]
@krmahadevan 

When you say `no-op`, you mean `no-aop`, right?
`no-aop` is just a Guice flavor without the aop feature:  https://github.com/google/guice/wiki/AOP#limitations
I suppose this choice was due to android purpose.

BTW, your questions are exactly why I'd like to remove the strong dependency on Guice: move the responsibility of guice version from testng to the user.
But the current PR shows that the Guice API didn't change: 4.x or 5.x should be the same and the users can override the version they want if the default one is not good for them.
Maybe the guice dependency should be optional.

**Comment by krmahadevan** [comment]
@juherr 

> When you say no-op, you mean no-aop, right?
Yes, I meant `no-aop`. My bad on the confusion.

Ok. I never actually delved into looking at what is part of the no-aop. It seems that its contents is almost the same as the actual guice dependency. I was thinking that only the bare interfaces are part of it (Something like what we are proposing `testng-api` and `testng-core`).

> Maybe the guice dependency should be optional.

I never have spent time trying to figure out gradle in detail. But doesnt `"guiceApi"(it)` mean that its a runtime dependency for us (may be because we have tests that need it for execution)

So we can go ahead and merge this PR ?

**Comment by juherr** [comment]
> But doesnt "guiceApi"(it) mean that its a runtime dependency for us

It is/was already a kind of modularization.

> So we can go ahead and merge this PR ?

Sure :)
