### ISSUE TITLE
dependsOnMethod broke on M1/Big Sur?

### ISSUE THREAD

**Issue by idontusenumbers** [cbeust/testng#2615]
### TestNG Version
7.4

I'm running Selenium tests using TestNG on a mac through Gradle. I recently moved from Intel running High Sierra to M1 running Big Sur.

When I run individual test classes that have `@Test` methods with `dependsOnMethod`, they run fine. However, when running the whole suite, those test classes seem to hang on the first `dependsOnMethod` test. These tests ran fine before I upgraded my computer; same code.

I've merged those test methods for the time being and the tests run fine now.

**Comment by juherr** [comment]
How can we reproduce the issue?

If your project didn't change, why do you think it is a TestNG issue?

Could provide us the exact current and previous jvm version?

**Comment by idontusenumbers** [comment]
I have no tired to reproduce. I just wanted to post my notes in case someone else ran into a similar issue.

I presume it's a TestNG issue because no matter how many times I ran my tests, it always hung (never finished those test classes and never started those test methods) on the tests with dependsOnMethod. If it were a race condition, it would not have been as consistent. I had tests like `a` and `b(depends on a)`; `a` passed but `b` never started. I triple checked this by attaching an ITestListener to log all the transitions.

My test classes held on to Selenium drivers until all test methods completed. With 4 classes with dependsOnMethod tests, I ran out of available Selenium sessions causing numerous timeouts as new tests failed to connect.

I don't know what the old version is/was, the disk died; it was 11 something.

New version:
```
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

**Comment by krmahadevan** [comment]
@idontusenumbers - And what happens when you try to create a similar test class, but without your selenium code? Do you see the hanging behavior there as well? If you dont see it, then it means that there's something in your selenium test that is causing things to stall. If its a chrome based test, please check if your chromedriver binaries are upto date. That's usually one thing that can cause failures. The same case with geckodriver if you are on firefox.

**Comment by idontusenumbers** [comment]
I'm using selenium docker containers. I'm using 4.0 beta because of the M1 business.

After removing all the dependsOnMethods, all the tests pass. Before that, zero of the tests with dependsOnMethod would pass; none of them even started.

**Comment by krmahadevan** [comment]
@idontusenumbers - That still doesn't pin the root cause to be on TestNG. If you can run a sample that doesnt have any selenium dependency with the same structure, then its definitely something going wrong in your code. Either ways, please do share a reproducible sample for us to move forward with figuring out what's going on in this issue. Without a sample, we cant do much, because `dependsOnMethods` is a very basic feature of TestNG and we have a lot of unit tests that check various different permutations and combinations

**Comment by idontusenumbers** [comment]
Is it possible TestNG is de-prioritizing test classes where some test methods have run but test methods marked dependsOnMethod have not yet run, while scheduling not-yet-run test classes first? This would explain what I'm seeing.

I'm not sure how M1 or Big Sur could exacerbate this issue. I know M1 has heterogenous cores and might have different thread scheduling as part of that architecture.

**Comment by krmahadevan** [comment]
@idontusenumbers Testng builds a DAG ( directed acyclic graph ) wherein the independent methods get executed first and after their completion the dependent methods get scheduled for execution. 

That is all that Testng does. That is why it's important that we see a sample to be able to reproduce this. 

Also have you seen this same behaviour in a different machine ( maybe a VM on the cloud for eg or a colleagues machine which is not using M1)? That would clarify the role of the M1 processor ( if any at all ).

**Comment by idontusenumbers** [comment]
It's possible this was indirectly caused by the M1 upgrade as I had to upgrade my selenium nodes and it's possible that ended up going from a node with unlimited sessions to one with limited sessions.

I might suggest prioritizing "has dependents that have been satisfied" over all other test methods. Conceptually, it makes a lot more sense for dependent method 'chains' to execute in sequence. As you describe, with all non-dependent methods going first, you get a HUGE gap/delay between dependent methods and their dependencies.

You're welcome to close this; I think talking through this we figured out what's going on.

**Comment by krmahadevan** [comment]
@idontusenumbers 

> I might suggest prioritizing "has dependents that have been satisfied" over all other test methods.

Its not that straightforward, considering the additional use cases that TestNG also supports viz.,

* Group by instances
* dependsOnMethods (wherein a downstream method has multiple upstream dependencies)
* dependsOnGroups
* priorities

> Conceptually, it makes a lot more sense for dependent method 'chains' to execute in sequence. As you describe, with all non-dependent methods going first, you get a HUGE gap/delay between dependent methods and their dependencies.

Yes conceptually it makes sense. But like I said, that's not the only use case that TestNG supports and the current implementation of forming a DAG wherein the earlier nodes represent independent methods and the later nodes representing dependent methods is the easiest way of visualising them. That doesn't mean that TestNG is going to wait for all independent methods to be run, before running the dependent methods. That was just me oversimplifying the internal workings of TestNG.
In reality, TestNG just walks through the DAG and starts picking up nodes (which represent a unit of execution) as and when it is made available to it. The DAG implementation is smart enough to start providing even dependent methods for execution, as and when its upstream dependencies have been satisfied.

>  I think talking through this we figured out what's going on.

Glad to know that the conversation helped in bringing this to a closure. Infact, you could have arrived at that consensus on your own, the moment you decided to break down the parts of your system and then isolate them individually to find out if they were the causes. So in your case it would have been the following:

1. Did something change in my test cases/framework ?
2. Can I reproduce the same problem with a simple plain vanilla TestNG test
3. If I am using a remote execution environment, did something change there with respect to the number of concurrent sessions (maxSession per Grid Node) or did we have one or more nodes go down while the execution was happening (unless you have a monitoring system to keep an eye on your nodes or you have a self healing grid such as this prototype that I built called [just-ask](https://github.com/RationaleEmotions/just-ask) wherein the grid is capable of healing itself by restarting nodes and then wiring them back in, the moment it goes down) which caused the overall parallel execution capability of the Grid to go down.

**Comment by idontusenumbers** [comment]
Would providing more control over the DAG walking make sense? I could see a few options 
1. Whatever it's doing now, which seems to be causing huge gaps between dependent methods (spread chains out due to current natural ordering)
2. Prioritize methods that have all their dependencies satisfied, which is what I was proposing earlier (execute chains up front)
3. De-prioritizing all methods that are depended on (delay chains till the end)

With the current implementation, heavy-weight or resource-constrained class-level resources (like the selenium sessions in my case but possibly memory in others) get 'locked' and the 'release' is delayed. This could cause any number of issues.

I realize the issue I ran into is entirely due to the way I'm allocating class-level selenium sessions, but it would be nice if TestNG didn't default to this sort of 'let the developer shoot their own foot'. Though I could see options 2 or 3 that I listed might cause similar issues for others.

Regarding selenium specifically, the current moment in time is pretty frustrating as Apple moved to M1 prematurely (IMHO) when Docker and other supporting tools weren't yet ready; Selenium development has slowed/stopped in preparation for version 4; default Selenium builds are x86 only; the one ARM build I found is behind and control over session count is apparently incomplete/nonexistent.

As part of this restructuring/upgrading due to M1, I'm replacing my Hub+node selenium docker-compose services with just a standalone. I'm relying on test class completion to release class-level selenium sessions. The actual node never dies, but the limited sessions get held open between the time TestNG starts the class but postpones execution of the test methods with decencies.

With the default 4 session max, the 4th test class that has a dependent method hangs on to that fourth and last available session; meanwhile TestNG moves on to a 5th test class, which then tries to grab a session, and hangs waiting for one since none are available. I have test failure handlers to take screenshots, which then request their own selenium session; in the end, every single test method after that 4th class is postponed takes 2 minutes to timeout (one for the session to use for the test and another for the session to use for the screenshot; though I've changed the screenshot implementation code to ignore test failures caused by selenium session timeouts). It *looks* like the selenium session for those 4 hung test classes broke some how, but now I realize whats going on: all the rest of those test methods were put at the end of the queue (figuratively).

**Comment by krmahadevan** [comment]
@idontusenumbers 

> Would providing more control over the DAG walking make sense? 

Sure we can look at it. But for that, we need you to help share a sample example that can be used to recreate the problem at hand. Without a sample, its going to be difficult.

> Regarding selenium specifically, the current moment in time is pretty frustrating as Apple moved to M1 prematurely (IMHO) when Docker and other supporting tools weren't yet ready;

Yes I stumbled into something related to this, when I was exploring getting myself a new Mac Mini with the M1 processor and just to be on the safer side, I googled up for developer experiences with M1 processor and the first thing that stood out was Docker going crazy with M1 and that was good enough for me to abandon that aspiration of pursuing an M1 atleast for the time being.

> Selenium development has slowed/stopped in preparation for version 4; default Selenium builds are x86 only; the one ARM build I found is behind and control over session count is apparently incomplete/nonexistent.

I am not quite sure I understand what you are referring to when you say `Selenium builds`. If its the grid component, then it should really not matter as to what is the underlying hardware architecture because AFAIK the selenium grid comes only in Java. Which would essentially mean that the misbehaviours (if any) are actually due to how Java works on the M1 rather than the Selenium Grid being branded as the culprit.

> With the default 4 session max, the 4th test class that has a dependent method hangs on to that fourth and last available session; meanwhile TestNG moves on to a 5th test class, which then tries to grab a session, and hangs waiting for one since none are available.

If I understand you correctly, 
* you have "n" test classes 
* each test class has "2 or more methods which uses `dependsOnMethods`
* Your Selenium sessions are being shared by the individual `@Test` methods that belong to the same test class
* You are using `parallel=class` for obvious reasons (since you want parallelism at the class level, since method level parallelism is ruled out due to dependencies)
* Your parallelism thread count is hard coded to some value which doesn't really take into account the max Session value that is available at the Grid side.

You could tweak this behavior by making the threadcount be set dynamically by perhaps seeing if `IAlterSuiteListener` can be leveraged to set the thread count. That should atleast have your executions (individual execution ofcourse) be aligned to the max session count that is supported at the Grid side. The `IAlterSuiteListener` could query the grid to find out what is the max Sessions being supported and adjust its thread count accordingly. Ofcourse this still doesnt shield you from the fact that there could be other users who are also running their tests against the same grid and they also end up running with the same thread count which means (2 users, start their tests with 4 as thread count, which means totally 8 sessions are needed, but the grid can offer only 4, so the other 4 obviously go into a new session request queue and we are back to square one).

You could also add another layer of sophistication wherein, you can do the following:

1. Check what is the current size of the new session request queue (I dont know if there's an API already available in the Hub or if you need to build a custom servlet that can do this for you)
2. If the size of the queue is large enough (define your own arbitrary value as to what determines a large value and a small value), you can instruct the grid to scale up (This would be the tricky part, because now you would need to figure out a way to talk to a VM to have it booted up and then wired in. Theoretically possible, of-course some research is needed)

Another thing you could do is, abort your test execution at the beginning itself if the new session request queue is very long.

> I have test failure handlers to take screenshots, which then request their own selenium session; 
This sounds fishy. The failure handler that is aiming at taking screenshots, should use the same selenium session, else you are going to get screenshots from a different browser, because session in the selenium world is a way to identify which browser instance on which node to interact with.

**Comment by idontusenumbers** [comment]
> I am not quite sure I understand what you are referring to when you say Selenium builds.

The official docker builds. I could build my own image with Grid and driver etc but that's not something I want to maintain.

> If I understand you correctly,

You understand correctly. The thread count is still less than the implicit session max. The issue isn't the thread concurrency, it's the order in which the individual test methods are run.

> This sounds fishy. 

It is fishy. It was using a method I have in my base test classes to grab a web driver, which if one was already assigned to that class, it grabbed it (reusing the existing session) and if one did not yet exist for that class, it created a new session, which is obviously nonsensical. Theoretically, aside from this case where a session failed to be established, there shouldn't exist a test failure such that there isn't already an established session that could be used.

Here's a visual aid for what I believe is happening now vs the two proposals I made earlier:
![image](https://user-images.githubusercontent.com/1175031/126845764-a491ecc9-77a8-4295-9710-28e48b877411.png)

**Comment by krmahadevan** [comment]
@idontusenumbers - Ok, so does it mean that your every `@Test` method doesn't release sessions after its done ? I was first assuming that your sessions are spanning across `@Test` methods of the same test class (i.e., you are using something like a  class level browser session) and so your dependent methods would use the browser session from the upstream test method. But if your `@Test` methods are NOT sharing sessions with dependent test methods, then they should close sessions right away.

**Comment by idontusenumbers** [comment]
You're original assumption was correct; they are class-level browser sessions.
