### ISSUE TITLE
ITestListener/onTestFailure Not doing anything

### ISSUE THREAD

**Issue by garyc0221** [cbeust/testng#2717]
### TestNG Version
7.5

### Expected behavior
ITestListener picks up failed tests and performs a screenshot. Previously worked on 7.4.0

### Actual behavior
Test not being detected as failed, so inside methods not being ran.  

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

This code previous to 7.5 would run and perform the methods within. When I update to 7.5 the listener doesn't seem to pick up the tests even though the listener is stated on every class.
Has something changed?

Test classes are using Annotation @Listeners({TestListener.class})

```java
package TestListeners;
import org.testng.ITestListener;
import org.testng.ITestResult;

public class TestListener1 implements ITestListener {

    @Override
    public void onTestFailure(ITestResult iTestResult){
        System.out.println("Test has failed");
    }

}
```
Test
```java
package TestListeners;

import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners({TestListener1.class})
public class SimpleTestFailure {

    @Test
    public void sampleTest() {
        throw new AssertionError("force fail");
    }

}
```
Output:
```
java.lang.AssertionError: force fail

```

**Comment by krmahadevan** [comment]
Please attach a simple example ( without selenium or any other 3rd party jars ) that can be used to reproduce the problem.

**Comment by garyc0221** [comment]
> Please attach a simple example ( without selenium or any other 3rd party jars ) that can be used to reproduce the problem.

Updated issue. Can see that test has failed does not print.

**Comment by krmahadevan** [comment]
@garyc0221 

That is what I thought as well. So can we close this ticket ?

Just a random suggestion:

Assuming that nothing changed in selenium version, on possible change can be that 7.5 onwards TestNG has moved to using slf4j logging facade. TestNG still would need you to provide one of the slf4j implementations ( since it just brings in the API ). 

Please check on those aspects as well just to be sure that this is not the cause.

**Comment by garyc0221** [comment]
@krmahadevan 
 
Yea Im replicating the error by just changing the testNG version in my pom.xml. 

In my pom.xml I have slf4j defined. Is version 1.7.31 compatible?

**Comment by krmahadevan** [comment]
Should be I guess. TestNG brings in 1.7.32 ( api alone and not any implementation such as log4j or jdk logger or simple logger or logback ).

**Comment by garyc0221** [comment]
@krmahadevan 

I'm thinking it just may be an incompatibility between TestNG 7.5 and Selenium 4.1.1 or Allure 2.17.2

Cant understand why it would just stop working when I change from testng 4.4 to 7.5

Unfortunately, that's my only replicable step

**Comment by krmahadevan** [comment]
@garyc0221 i can try taking a jab at it since I am a selenium literate. 

Can you please create a sample project and attach it here which uses all the dependencies that your actual project has and which has a failing test along with a failure listener that takes screenshots?

Keep it as close to your actual project as possible so that we are looking at a replica of your actual project.

**Comment by garyc0221** [comment]
@krmahadevan

Sorry for the long reply.

Was having a lot of trouble trying to replicate the problem.

I have found the issue. When using testNG version 7.5 allure cannot add attachments as it is saying test is not running anymore

Jan 14, 2022 1:16:12 PM io.qameta.allure.AllureLifecycle prepareAttachment
SEVERE: Could not add attachment: no test is running

**Comment by krmahadevan** [comment]
@garyc0221 - Then I think you would need to take this up with Allure. So we can perhaps go ahead and close this out ?

**Comment by garyc0221** [comment]
> @garyc0221 - Then I think you would need to take this up with Allure. So we can perhaps go ahead and close this out ?

Yes can close this issue
