### ISSUE TITLE
@AfterMethod method not executed when @Test method is skipped (TestNG 6.8)

### ISSUE THREAD

**Issue by xiaoyichengp** [cbeust/testng#325]
Hi, i declare an ITestResult in my @AfterMethod method:

```java
@AfterMethod (awlaysRun=true)
public void after(ITestResult tr)
 {
    int status = tr.getStatus(); // ITestResult.SUCCESS, FAILURE or SKIP
    System.out.println(status );
 }

@Test
public void testMethod1(){
    assertEquals(1,2);
}

@Test(dependsOnMethods = { "testMethod1" })
public void testMethod2(){
    System.out.println("");
}
```
---

`testMethod1` is failed, and `testMethod2` is skipped.

My issue:
why did it not print test Status of `testMethod2` in `@AfterMethod` method? In other words, why testng does not run `@AfterMethod(awlaysRun=true)` when a test method is skipped?  (TestNG 6.8)

**Comment by krmahadevan** [comment]
It makes sense for configuration methods to be run before test methods that would/have run. So it makes sense for TestNG to run them for passed and failed methods. But when a test method is being skipped, then it doesn't make any sense for TestNG to run `@AfterMethod` methods for it, because the test method itself is not eligible for execution.
