### ISSUE TITLE
testng does not respect "-parallel classes" when running with a jar file

### ISSUE THREAD

**Issue by realfun** [cbeust/testng#341]
## I have 2 test classes in my package and build into a jar, there is no testng.xml in the jar

```
public class T1 {
@Test public void test() throws InterruptedException {
    for (int i=0; i<3; i++) {
        System.out.println(this.getClass().getName());
        Thread.sleep(1000);}}}


public class T2 {
@Test public void test() throws InterruptedException {
    for (int i=0; i<3; i++) {
        System.out.println(this.getClass().getName());
        Thread.sleep(1000);}}}
```

After that I ran with -testclass & -parallel classes, it will run in parallel:

```
$ java -cp jcommander-1.27.jar:testng-6.8.jar:target/ohmy-0.0.1-SNAPSHOT.jar org.testng.TestNG -parallel classes -testclass frank.ohmy.T1,frank.ohmy.T2
```

---

```
[TestNG] Running:
  Command line suite

frank.ohmy.T1
frank.ohmy.T2
frank.ohmy.T1
frank.ohmy.T2
frank.ohmy.T1
frank.ohmy.T2

===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================
```
## But if I run with -testjar & -parallel classes, it will _NOT_ run in parallel:

```
$ java -cp jcommander-1.27.jar:testng-6.8.jar:target/ohmy-0.0.1-SNAPSHOT.jar org.testng.TestNG -parallel classes -testjar target/ohmy-0.0.1-SNAPSHOT.jar
[TestNG] Couldn't find the testng.xml in the jar file, running all the classes
frank.ohmy.T1
frank.ohmy.T1
frank.ohmy.T1
frank.ohmy.T2
frank.ohmy.T2
frank.ohmy.T2
```

Seems like a testng bug, I run on 6.8, also tried build from github version, still repro.

**Comment by StdVectorBool** [comment]
I think the bug is that `XmlSuite.setParallel()` is only called for `m_cmdlineSuites`:
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L902

and not for suites added directly to `m_suites` such as in the JAR code path:
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/TestNG.java#L373

**Comment by juherr** [comment]
@StdVectorBool You may have found the issue. Do you want to propose a fix?

**Comment by StdVectorBool** [comment]
I was going to extract a new method from the loop body of `initializeCommandLineSuitesParams` and re-use it in `initializeSuitesAndJarFile`.

Seems like a straightforward fix, but I'm struggling with the unit tests:
* [Travis results](https://travis-ci.org/cbeust/testng/builds) have had test failures for over a month
* [JAR tests](https://github.com/cbeust/testng/blame/master/src/test/resources/testng.xml#L108) were disabled 5 years ago
* Even after fixing the test's [JAR initialization](https://github.com/cbeust/testng/blob/master/src/test/java/test/jarpackages/JarPackagesTest.java#L18), unsure how to get the JAR into the ClassPath so that the rest of the test runs.

Any hints on fixing up that test?
It only needs to verify [SuiteRunner](https://github.com/cbeust/testng/blob/15a824bd8d3658e7070b7cf105f2adc011d07000/src/main/java/org/testng/SuiteRunner.java#L339) doesn't call the `runSequentially` method, so is it likely some Spock mocking will work better than what's there now?

**Comment by juherr** [comment]
Don't worry about Travis, tests are ok but we have random results (and we don't know the reason for the moment).

The disabling of the tests without any clues is strange but in this situation and if you don't find how to fix it, I think we will accept a pull request without a test.

Thanks for your feedback.
