### ISSUE TITLE
Parallel DataProvider and Suite parallel settings

### ISSUE THREAD

**Issue by twloda** [cbeust/testng#485]
Test method that uses dataprovider doesn't follow parallel settings from suite.
1. 
suite file: 
```xml
<suite name="ParallelSuite" parallel="methods">
```
data provider:
```java 
@DataProvider
public Iterator<Object[]> dataProvider()
```

Test method that uses this data provider method is executed sequentialy. This behavior is acceptable.

2.
suite file:
```xml
<suite name="ParallelSuite" parallel="false">
```
data provider: 
```java
@DataProvider(parallel=true)
public Iterator<Object[]> dataProvider()
```

Test method that uses this data provider method is executed with random parameters order. I think that this is a bug. In that case I expect that test methods will be executed sequentialy as set on suite level.

**Comment by krmahadevan** [comment]
ping @cbeust @juherr WDYT ?
The ask here is that when a user sets `parallel=false` at `<suite>` level, then parallelism should be disabled, even if a `@Test` method has its data provider defined as `@DataProvider(parallel=true)`.

**Comment by juherr** [comment]
@krmahadevan I disagree because the current behavior is "children override parents" everywhere.

**Comment by krmahadevan** [comment]
@juherr 

But that rule doesn't seem to be applicable to data providers. You can set the data provider thread count at the suite level and at the test level, but still I don't think parallel executions happen for data providers unless and until the `parallel=true` attribute is set. Moreover I don't think there is any way in which you can enable/disable the data provider parallel execution behavior from the xml file.
So it looks like data provider is kind of agnostic/not impacted by the xml configurations. I feel that we should get this sorted out in some manner (Maybe add a new attribute to the TestNG xsd which will let users govern this from the suite file).

**Comment by juherr** [comment]
@krmahadevan I think it should be easy to fix the issue with an `IAnnotationTransformer2` and change the value if the current behavior is not the expected one by the user.

IMO, the issue should be closed.

**Comment by krmahadevan** [comment]
Closing this issue since an alternative exists for getting this done from within the user's project itself via an `IAnnotationTransformer2` implementation.

**Comment by herronism** [comment]
Can you share an example of the `IAnnotationTransformer` solution?

I'm working on a testing framework which contains a mix of DataProvider and non-DataProvider tests.

**Current Behaviour**
In testing.xml, setting `parallel="xyz"` applies only to tests that don't use a @DataProvider. For example, if I set this to `parallel="none"` and run all my tests, my @DataProvider tests run in parallel because the `@DataProvider(parallel = true)`overrides the XML. If I remote the `parallel` attribute from the DataProvider, then those tests will NEVER run in parallel irrespective of what I put in my XML file.

**Desired Behaviour**
- Setting `parallel="none"` in the XML results in NO tests running in parallel - each test runs one at a time.
- Setting `parallel="[methods/suites/etc]"` in the XML results in tests running in parallel - including the DataProvider and non-DataProvider tests.


I don't think the documentation is very clear on this. My understanding was originally that `@DataProvider(parallel = true)` was needed to _allow this data provider to run in parallel_ but I see that it now this actually forces these tests to run in parallel.

I want my testers to modify the XML file to change the level of parallelism - I don't want them to have to open the data provider class and make any changes.

Any ideas?
