### ISSUE TITLE
Setting TestResult status to FAILURE via Reporter not causing test to fail

### ISSUE THREAD

**Issue by customer37** [cbeust/testng#514]
I am setting the status in the TestResult for the Reporter as follows:

Reporter.getCurrentTestResult().setStatus(ITestResult.FAILURE);

Under the results section of the index.html report, the test shows as Passed still.  I print out TestResult to the Reporter Output section and it shows:

[TestResult name=registration_test status=FAILURE method=SeleniumAutomation.registration_test()[pri:0, instance:Selenium.SeleniumAutomation@10d55478] output={null}]

So the status is being updated.  The test is not failing though.

**Comment by krmahadevan** [comment]
This is not an issue. If a `@Test` method's result is to be altered, then it should be altered via one of the TestNG listeners and not via `Reporter.getCurrentTestResult().setStatus(ITestResult.FAILURE);` because `Reporter.getCurrentTestResult()` just queries a `ThreadLocal` copy of the `ITestResult`
