### ISSUE TITLE
Issue with ITestAnnotation.setdataProvider() methods.

### ISSUE THREAD

**Issue by virenv** [cbeust/testng#580]
Hi,

I have been scratching my head over this issue for past two days.
Scenario: I am listening to the transform events on IAnnotationTransformer<2> and IMethodInterceptor interfaces. In the 

```
transform(ITestAnnotation annotation, Class testClass,
            Constructor testConstructor, Method testMethod)  
```

I change the DataProvider and DataProviderClass values using the annotation.setDataProvider
and annotation.setDataProviderClass methods. 

Now after this I have to read the DataProvider value of all the methods in the `intercept(List<IMethodInstance>` methods,
            `ITestContext` context) 
method. Here I am getting value like this

``` java
            for (IMethodInstance method : methods) {                
                String dataProviderName = method.getMethod()
                        .getConstructorOrMethod().getMethod()
                        .getAnnotation(org.testng.annotations.Test.class)
                        .dataProvider();
                                                   ...........
```

Issue: I am getting dataProviderName  as blank.

You can look at the code file here
https://github.com/virenv/omelet/blob/master/src/main/java/com/springer/omelet/testng/support/RetryIAnnotationTransformer.java

I am not sure what exactly is happening here. Could you please elaborate if its wrong usage or a bug?

Thanks
Virender

**Comment by virenv** [comment]
Thanks for no comments. But I manage to figure this out (for those of you who might fall in this problem). The reason for this is because events to annotation transformer and method interceptors go on separate threads and at a point in time when the method's annotation is not updated.

**Comment by krmahadevan** [comment]
@virenv 

The line 

```java
method.getMethod()
                        .getConstructorOrMethod().getMethod()
                        .getAnnotation(org.testng.annotations.Test.class)
                        .dataProvider();
```
basically is querying the actual class map that resides internally in the `java.lang.Class` for retrieving the annotation values. TestNG does not alter this map, when it exposes the methods to be transformed via an `IAnnotationTransformer` implementation. So any changes made via a transformer are going to be known only to TestNG, but not to the JVM (which is what gets queried via the `getConstructorOrMethod().getMethod()`).

AFAIK, there's currently no way to figure out what is the actual data provider that is going to be used with a `@Test` method (After it has been transformed via an `IAnnotationTransformer` implementation) 

So if you would like to read the altered values after its been changed via an AnnotationTransformer, you may also have to do something like what I explain in [this](https://rationaleemotions.wordpress.com/2016/05/27/changing-annotation-values-at-runtime/) blog post of mine, so that it can be read via the MethodInterceptor.

Am closing this issue for now as *Question answered*. Please feel free to comment or open a new one if you still face issues.
