### ISSUE TITLE
Testng runs custom listener if there is at least one test case that uses this custom listener (only happens in package execution using Bean Shell)

### ISSUE THREAD

**Issue by prvn133t** [cbeust/testng#627]
Let's say I have a package `com.fwork.cases` and a few tests in this package as shown below
1. `FirstTest.java`
2. `SecondTest.java`

Let's say the class `SecondTest.java` uses a custom listener as below
```java
@Listeners({ com.fwork.report.Report.class })
```

`FirstTest.java` does not call the `Report.class` listener. 

Now If I run the `FirstTest.java` test case individually using eclipse (not using `testng.xml`)  it runs fine without calling the `Report.class` listener. However if I use a `testng.xml` and use Bean Shell to call the test using test name it calls the Report.class listener for the `FirstTest.java` too.

I'm using the following to call the test name in the `testng.xml`

```xml
<method-selector>
    <script language="beanshell">
                <![CDATA[testName = System.getProperty("testName");
                method.getDeclaringClass().getName().contains(testName);]]>
    </script>
</method-selector>
```

**Comment by juherr** [comment]
And what appends if you use eclipse AND testng.xml?

If it works, it will be a Bean Shell issue, isn't it?

**Comment by krmahadevan** [comment]
@juherr - I am guessing that this issue boils down to TestNG not associating context when it runs listeners (especially the ones that are injected via `@Listeners`). Today TestNG just collates all the listeners that were added by the user by all the means ( via the `<listeners>` tag or via the service loaders approach or via the `@Listeners` annotation) and then runs them for a given suite (if its a default suite that TestNG creates when a user right clicks a test and runs it via their favorite IDE or via the command line).

So in that suite, if TestNG finds at-least one listener, then it gets applied to all the classes.

I am guessing that the ask here is that, TestNG choose to run a listener injected via `@Listeners` annotation, only to the class on which this annotation was found.

Please let me know if my understanding on this issue is correct.

**Comment by juherr** [comment]
@krmahadevan True. `@Listeners` has no scope and the declaration is global to all the suite.
