### ISSUE TITLE
After getting update tesng (6.9) in my eclipse IDE, Not able to run testng.xml

### ISSUE THREAD

**Issue by pradeepgoyal** [cbeust/testng#820]
I just updated testng in eclipse IDE or install new testng software with my eclipse using youu given URL 
- http://beust.com/eclipse/
After that i am not able to run my test case by tesng.xml but i am able to run test case (.java class) separately by testng.

Note: on click on "http://beust.com/eclipse/", i am also getting below error :- 
Forbidden
You don't have permission to access /eclipse/ on this server.

But tesng software is successfully installed in my eclipse IDE

**Comment by verhagen** [comment]
After downloading [Eclipse Mars (v4.5) for Java development](http://www.eclipse.org/downloads/) and installing TestNG through the [Eclipse Market Place](http://marketplace.eclipse.org/content/testng-eclipse). This installs the same version as when done through Eclipse Update site (http://beust.com/eclipse/).

Then successfully run the test cases through the _Eclipse Run As -> TestNG Tests_.

As well as using Maven test, where there are some `testng*.xml` files. They did run successfully as well.

It seems to me that it has to do with your set up, and / or the _System Under Test_.

__Remark__

The __Error__ you see when accessing the Eclipse update site (http://beust.com/eclipse/) is because it is not ment for reading. It just contains the content files, for Eclipse to read, the TestNG plug-in details.

__Questions__

- Which version of Eclipse are you using?
- Where does the message _You don't have permission to access /eclipse/ on this server._ come from?
- Can you share what and how you're testing?

**Comment by verhagen** [comment]
@pradeepgoyal There is indeed an issue with, running TestNG test form a testng.xml file. Can you confirm the issue description and also if the workaround works for you?

__Issue Description__
When selecting a `testng.xml` file from the _Package Explorer_ view, and use the right mouse button menu: _Run As -> TestNG Suite_, then it will not run the tests.

__Workaround__
- From the Eclipse menu select: _Run -> Run Configurations..._
- The dialog _Run Configurations_ opens
- Select from the tree on the left _TestNG_
- Use the right mouse menu: _New_ (or use the shortcut icon on the top of the tree _New Launch Configuration_)
- A new _TestNG Run Configuration_ will open on the right
- Fill in the field _Name_ a useful name for this configuration
- Select under _Run..._ the radio button _Suite_
- Use the button _Browse..._
- A dialog _Available suites_ opens
- Select the TestNG Suite(s) for this configuration
- Use the button _OK_ to close the dialog
- Use the button _Run_ to run the TestNG suite(s)

See also [Create TestNG Launch in Eclipse](http://testng.org/doc/eclipse.html#eclipse-create-launch)

**Comment by missedone** [comment]
I confirm it's a bug, will fix it later.

**Comment by varunsharma09** [comment]
suggested work around fails with inherited classes.

**Comment by missedone** [comment]
@varunsharma09 
> suggested work around fails with inherited classes.

are you facing the issue similar as https://github.com/cbeust/testng-eclipse/issues/70 ?
